### ISSUE TITLE
Investigate CMS Options

### ISSUE THREAD

**Issue by nelsonic** [LDMW/app#1]
***Relevant Content*** is a _big_ part of this project.

## Requirements

+ [ ] Create/Update Content using an intuitive UI
+ [ ] Easily add other media types (_e.g. images in posts or videos hosted on other platforms_)
+ [ ] Render content in a mobile-friendly way
+ [ ] SEO/Google Friendly pages with metadata/tags and descriptive/human-friendly URLs
+ [ ] Easy to deploy to our hosting service (_currently Heroku_)

### Wagtail CMS?

Someone on the initial project call mentioned that other Gov agencies are using https://wagtail.io 
see: https://github.com/wagtail/wagtail
we need to try and run Wagtail locally to check what we _can_ use.

If we determine that it's easy enough to run locally we could attempt to deploy it on Heroku and let LDMW team have a play with it.

cc: @shouston3

**Comment by shouston3** [comment]
A fairly comprehensive overview of what wagtail has to offer can be found from the two links "check out the features" and "watch demo" from https://wagtail.io/

I've managed to get it running locally, and configuring postgres (from SQLight default) was also not too much trouble. When running with postgres we are given the following tables:
```
public | auth_group                                    | table    | samhouston
 public | auth_group_id_seq                             | sequence | samhouston
 public | auth_group_permissions                        | table    | samhouston
 public | auth_group_permissions_id_seq                 | sequence | samhouston
 public | auth_permission                               | table    | samhouston
 public | auth_permission_id_seq                        | sequence | samhouston
 public | auth_user                                     | table    | samhouston
 public | auth_user_groups                              | table    | samhouston
 public | auth_user_groups_id_seq                       | sequence | samhouston
 public | auth_user_id_seq                              | sequence | samhouston
 public | auth_user_user_permissions                    | table    | samhouston
 public | auth_user_user_permissions_id_seq             | sequence | samhouston
 public | django_admin_log                              | table    | samhouston
 public | django_admin_log_id_seq                       | sequence | samhouston
 public | django_content_type                           | table    | samhouston
 public | django_content_type_id_seq                    | sequence | samhouston
 public | django_migrations                             | table    | samhouston
 public | django_migrations_id_seq                      | sequence | samhouston
 public | django_session                                | table    | samhouston
 public | home_homepage                                 | table    | samhouston
 public | taggit_tag                                    | table    | samhouston
 public | taggit_tag_id_seq                             | sequence | samhouston
 public | taggit_taggeditem                             | table    | samhouston
 public | taggit_taggeditem_id_seq                      | sequence | samhouston
 public | wagtailcore_collection                        | table    | samhouston
 public | wagtailcore_collection_id_seq                 | sequence | samhouston
 public | wagtailcore_groupcollectionpermission         | table    | samhouston
 public | wagtailcore_groupcollectionpermission_id_seq  | sequence | samhouston
 public | wagtailcore_grouppagepermission               | table    | samhouston
 public | wagtailcore_grouppagepermission_id_seq        | sequence | samhouston
 public | wagtailcore_page                              | table    | samhouston
 public | wagtailcore_page_id_seq                       | sequence | samhouston
 public | wagtailcore_pagerevision                      | table    | samhouston
 public | wagtailcore_pagerevision_id_seq               | sequence | samhouston
 public | wagtailcore_pageviewrestriction               | table    | samhouston
 public | wagtailcore_pageviewrestriction_groups        | table    | samhouston
 public | wagtailcore_pageviewrestriction_groups_id_seq | sequence | samhouston
 public | wagtailcore_pageviewrestriction_id_seq        | sequence | samhouston
public | wagtailcore_site                              | table    | samhouston
 public | wagtailcore_site_id_seq                       | sequence | samhouston
 public | wagtaildocs_document                          | table    | samhouston
 public | wagtaildocs_document_id_seq                   | sequence | samhouston
 public | wagtailembeds_embed                           | table    | samhouston
 public | wagtailembeds_embed_id_seq                    | sequence | samhouston
 public | wagtailforms_formsubmission                   | table    | samhouston
 public | wagtailforms_formsubmission_id_seq            | sequence | samhouston
 public | wagtailimages_filter                          | table    | samhouston
 public | wagtailimages_filter_id_seq                   | sequence | samhouston
 public | wagtailimages_image                           | table    | samhouston
 public | wagtailimages_image_id_seq                    | sequence | samhouston
 public | wagtailimages_rendition                       | table    | samhouston
 public | wagtailimages_rendition_id_seq                | sequence | samhouston
 public | wagtailredirects_redirect                     | table    | samhouston
 public | wagtailredirects_redirect_id_seq              | sequence | samhouston
 public | wagtailsearch_editorspick                     | table    | samhouston
 public | wagtailsearch_editorspick_id_seq              | sequence | samhouston
 public | wagtailsearch_query                           | table    | samhouston
 public | wagtailsearch_query_id_seq                    | sequence | samhouston
 public | wagtailsearch_querydailyhits                  | table    | samhouston
 public | wagtailsearch_querydailyhits_id_seq           | sequence | samhouston
 public | wagtailusers_userprofile                      | table    | samhouston
 public | wagtailusers_userprofile_id_seq               | sequence | samhouston
```

From a brief look through a few of them, they seem pretty organised so I'm thinking should be fine to work with.

In terms of performance, I couldn't find any complaints online and they pride themselves on their performance here (although nothing specific to postgres - do you think there should be further investigation?): http://docs.wagtail.io/en/v1.9/advanced_topics/performance.html

From looking in `auth_user` I found a sha256 password hashing algorithm. This is the default used by django.

I couldn't seem to find where to configure this from the wagtail side of things, but django seems to say this [should be relatively easy](https://docs.djangoproject.com/en/1.11/topics/auth/passwords/)

My plan for now is to work out how to ensure new users are stored using bcrypt and then to proceed making new pages (with different things attached to them) and seeing how these are stored in postgres.

**Comment by ellemindwave** [comment]
@shouston3 @iteles @nelsonic Just checking where we are on this one? It was discussed that the investigations into CMS would be completed ahead of sprint 1 starting. Please could we have the documentation for your investigations so we can add to our system architecture report for the client? Thanks!

**Comment by shouston3** [comment]
@ellemindwave I investigated the wagtail cms prior to sprint 1 starting, but am yet to write up documentation on why Wagtail is a good cms choice, but I can give you a breakdown of my findings, what specifically would you like to know?

If I am to write up documentation, could I have a look at the current system architecture report so that I know the standards to abide by?

**Comment by iteles** [comment]
@elle India has also asked me this question on slack and I have answered her separately. I think that answering it in GitHub is _absolutely_ the right thing to do, so thank you for asking it here!
We were trying to get as much testing as possible done prior to the official start date so we reviewed @shouston3's research notes on a longer standup and he hasn't had a chance to write them up yet - only the conclusion as you have seen above. 

@shouston3, let's catch up on this on our call today :blush:

**Comment by iteles** [comment]
Note: this was done in sprint 0, but we do need to add our notes on the research.

**Comment by shouston3** [comment]
### Background
Wagtail is a relatively new CMS technology which has improved on the decisions made by it’s other Python CMS competitors.
It is built in python using the django framework. It is very performant and has a flexible configuration for database or other technology options.
### UI
Although Wagtail is build on top of django, the Wagtail team have rebuilt the UI from scratch. Mezzanine CMS or DjangoCMS are the two other big python cms alternatives, but their UI was just recycled from what Django offers. This UI is quite dated and what Wagtail offers is a much better alternative
### Facilitating inputting media types
This was another of the requirements laid out by Nelson and is fairly standard for a CMS.
Managing the alignment and size of the image is facilitated by Wagtail and is documented.
Video embedding was not documented, but would certainly be facilitated and would probably work in a similar way to image embedding.
### Programming language
The initial preference for programming language would have been for a Javascript or Elixir open source CMS.
The benefits of doing this would be that we would be able to seek help from the community and maintainers as well as giving back by improving the CMS.
Javascript did not have a real consensus for the best CMS to use. Keystonejs was built on Mongodb which is not as stable as postgres,
it was also not database agnostic or configurable which was an issue.
There were very few Elixir options with the main result having a commit over 1 year ago.
ButterCMS offered a CMS in both of these languages, but it was not free and was not open source
From realising that we wouldn’t be able to be familiar with the programming language or framework, we were free to choose the most current and performant CMS.
Drupal and Wordpress are some of the more popular CMS options, but Nelson had experienced issues where the Database was not performant and can slow down the site.
These are also written in PHP which is a notoriously unorganised language. Wordpress and Drupal also have long lists of Criticism.
Python is a very clean, stable, performant language and has a supportive community. Django is a very popular and stable python framework which is very configurable and flexible.
This combination has been used to build a number of popular CMS’s
### Database optimisation
This is quite a difficult specification to test. Wagtail promote their performance quite a lot on their site and have performance tests against their competitors.
As wagtail is relatively new, they have learnt from the database optimisation mistakes made by their competitors.
From looking at how their database is laid out, it is very organised is unlikely to have any problems associated with it.
### Deployment
Our initial deployment method would be through Heroku.
There are numerous articles on this and it would be a typical thing for a Wagtail developer to do, it is unlikely that there would be issues here.
### Open source
Wagtail is open source and has a thriving and growing community. The fact that it’s popularity is growing is also a sign that it’s being maintained as a technology.
Open source also means that we can see everything that is happening behind the scenes and that the code is constantly critiqued and improved.
### Password hashing
Wagtail’s password hashing system is easily configurable and can be layered. This is made possible by the Django framework.
### Conclusion
Wagtail is gaining all of the benefits of being a new technology from learning from it’s Django competitors, while remaining very robust by utilising a very stable Django framework and a very tested Python language
