### ISSUE TITLE
Domain Name

### ISSUE THREAD

**Issue by nelsonic** [LDMW/app#10]
if we want a _temporary_ domain name we could register ldmw.io or ldmw.co which are both _available_:
![image](https://cloud.githubusercontent.com/assets/194400/25228354/0ffde440-25c4-11e7-9ef0-8a35ad0d68ba.png)

do we want a domain that is a recognisable word or set of words, a "brand" or just a temporary one we can use to start _shipping_ to beta users?

**Comment by shouston3** [comment]
Sarah has purchased these: londonminds.co.uk and ourlondonminds.co.uk for the beta users

**Comment by ellemindwave** [comment]
- [ ] Set up server on Amazon (Sam / Dan) 
- [ ] Provide team with permanent, static IP address of the server (Sam / Dan) 
- [ ] Add IP address to GoDaddy account (Sarah / Elle)

**Comment by shouston3** [comment]
@sarahwelton We will initially set up a server on Heroku, then later look at Amazon.
This article gives a good comparison of the two: https://smashingboxes.com/blog/heroku-vs-amazon-web-services/
The static ip address of the server should be ready for you in the next couple of working days

**Comment by iteles** [comment]
Moving to milestone 2 as the requirement for password protection ahead of the election was added #39

**Comment by iteles** [comment]
#116 
<img width="621" alt="screen shot 2017-05-09 at 11 00 40" src="https://cloud.githubusercontent.com/assets/4185328/25845736/e21c6794-34a6-11e7-907e-027e66761ceb.png">

**Comment by Danwhy** [comment]
Site is up at www.londonminds.co.uk

**Comment by ellemindwave** [comment]
Woo hooo! Thanks
