### ISSUE TITLE
Article/Resource likes

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#104]
Should store the user's ip address of who clicked on the like/dislike button. That way we avoid people re-liking things when they refresh the page (thoughts @Danwhy @SimonLab ? Are there other ways we should look in to for doing this?)

Perhaps we should get google analytics working before implementing a plan for this to see what data we are collecting and what we could be storing about each visitor and match against their likes/dislikes.

**Comment by Danwhy** [comment]
Only allowing each IP address one like/dislike was my first thought too.
I don't think there's a problem with going ahead and building it without limiting the number of likes a person can give for now though, just for the first iteration.

**Comment by shouston3** [comment]
@Danwhy How much of the GDS requirements should be met with this?

Creating a form which reloads after every like increment seems a little painful (or a submit button for your like). Would you say the GDS requirements of no javascript should also be implemented here too?

**Comment by Danwhy** [comment]
Everything needs to work without javascript. A page reload may be a minor annoyance but we can add the `prevent default` javascript straight so that everybody that _does_ have javascript enabled doesn't get the reload

**Comment by shouston3** [comment]
Comprehensively answered @Danwhy thanks
