### ISSUE TITLE
'Success' message when a person submits their email in the alpha block at the bottom of the page

### ISSUE THREAD

**Issue by indiamindwave24** [LDMW/app#108]
As a user, I want to see a success message when I have input my email address so that I know my email address has been registered and I haven't made a mistake.

- [x] On correct entry of email address, user should click 'take part' and then see success message
- [x] If the email address is not valid, user should be alerted

<img width="486" alt="screen shot 2017-05-08 at 15 06 52" src="https://cloud.githubusercontent.com/assets/25007700/25808287/899884e0-3401-11e7-821f-5378e58f81c3.png">

**Comment by ellemindwave** [comment]
As a service provider, I want to gather email addresses of users who are interested in being involved with the alpha phase into a Google spreadsheet so that I can get in touch with them to give them more information, help them get involved and ask for valuable feedback

Relates issue #59

**Comment by iteles** [comment]
@indiamindwave24 By 'not valid', I assume you mean the traditional simple checks that are performed to ensure an email is in the right format? (i.e. xxx@xx.xx and includes an @ symbol).
Is that right?

**Comment by indiamindwave24** [comment]
yes @iteles 👍

**Comment by indiamindwave24** [comment]
I notice that the styling is not in line with the original designs - what is th reasoning behind this?

**Comment by shouston3** [comment]
@indiamindwave24 could you open one or more smaller issues for how the current styling is not in line with the original designs
Closing this larger issue and working from many smaller issues is easier for us to maintain

**Comment by indiamindwave24** [comment]
#187
