### ISSUE TITLE
Tip quote styling

### ISSUE THREAD

**Issue by indiamindwave24** [LDMW/app#111]
As a service user, I want the service to look professional so that I feel confident using it.

As a service user, I want the service to be pleasant to look at so that I enjoy using it.

<img width="237" alt="screen shot 2017-05-08 at 17 01 53" src="https://cloud.githubusercontent.com/assets/25007700/25813867/15966104-3413-11e7-8b13-26c9464de5b8.png">

- [ ] On same styled card as resources
- [ ] Centred dark blue quotation marks (nunito sans, bold, 34pt)
- [ ] Tip left aligned

**Comment by ellemindwave** [comment]
Closing this issue, as it is no longer relevant (tips will be styled differently to resources)
