### ISSUE TITLE
London Minds backlog grooming

### ISSUE THREAD

**Issue by iteles** [LDMW/app#113]
As a product owner (or as a scrum master), we want to have a clear and concise backlog so that it is easy to navigate and understand.

<hr/>

## Acceptance Criteria      

+ [x] @iteles takes a pass through the backlog and raises questions, tightens processes
+ [ ] @ellemindwave reviews the backlog (not including the [technical label](https://github.com/LDMW/app/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20-label%3Atechnical)) to make ensure it:
  + [ ] reflects the project requirements
  + [ ] all user stories have acceptance criteria (where they are known)
  + [ ] open questions are answered

**Comment by reddog** [comment]
@ellemindwave Do you think we've done that for this (Phoenix) repo?

**Comment by reddog** [comment]
@ellemindwave says `yes`!
