### ISSUE TITLE
Styleguide: dynamically updating/ generating style guide 

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#115]
At the moment the style guide found at '/styleguide' is hard coded (aside from the rendering standard components). As a result, this means that as components change/ new ones are added, there will not be content for these or the existing code screenshots may not reflect what is needed to use them.

**Dynamically display each of the standard components**
- [x] To overcome this problem, we need to create a script that will run and display each of the component files within the component folder automatically so that new ones/ deleted ones will immediately change on the '/styleguide' page. 

**Replace code screenshots to dynamically generated code snippets.**
- [x] Create a function to encode regular code using HTML entities or find a hex module that can do this.
- [x] Run this function on each of the example files.

**Styling**
- [x] Reorganise the styling with the newly rendered components
- [x] Create a function that will dynamically create sections based on the number of results for each of the component rendering functions.

**Testing**
- [x] Test each of the functions

**Refactor**
Check functions for any improvements.

**Comment by nelsonic** [comment]
@Cleop looks good. please post updates as comments so others can follow along
(_and future learners can learn from your quest_) thanks!

**Comment by Cleop** [comment]
The two functions (rendering components and rendering the component code) are working. However, now they need to be knitted together so that the results of each can be displayed together. 

I know that both functions are returning lists: one is a list of the relevant file names that need to be rendered and the other is a list of the code snippets that will be displayed. So `List.zip(eg_components, eg_component_code)` seemed like a good option. However this is creating the error:
![image](https://cloud.githubusercontent.com/assets/16775804/25909059/e32e1a80-35a3-11e7-9ac2-a5630579e68a.png)

I'm now going to look at why this error may be occurring and what kinds of values you can have in lists.

**Comment by Cleop** [comment]
@nelsonic - you mentioned each component having a test section. Can you elaborate what you meant by this?

We are already in the `components_to_code` function testing that the files contain what we expect them to contain.

I was trying to think if there was another way that I could test the component files themselves. All I could think of for this was to again, test what code they contain which could be done running something like:
```component("secondary_button", value: "Take assessment", to: "/info/coming-soon")|> Phoenix.HTML.safe_to_string```
which results with:
```"<!--For use on dark backgrounds-->\n  <a class=\"f5 link dib ph3 pv2 br-pill lm-bg-dark-blue lm-white-hover b--lm-white-hover lm-orange pointer ba bw1 b--lm-orange bg-white \" href=\"/info/coming-soon\">Take assessment</a>\n"```

But is this what you had in mind? Is this achieving anything more than the existing and test components_to_code function?

**Comment by nelsonic** [comment]
@Cleop did you make a note of the diagram sketched out last Friday?

**Comment by Cleop** [comment]
@nelsonic, yes, that's where you mentioned tests. So I gathered that you had envisaged tests, it's more (having not tested components like this before) that I wanted to understand what you wanted these tests to look like?

I also noted down roughly what you wanted for the style of the component guide but at the time it was a rough sketch (like a wireframe as opposed to a design) and so I wanted to see if you had anything more specific in mind. But if you're happy for me to proceed then I will with the styling.

**Comment by shouston3** [comment]
Fixed by #123 

We need to tidy up some of the remaining components just used for testing
