### ISSUE TITLE
All “all” to the filter options

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#127]
As a user, I want to be able to select all the options when filtering so that I can see the most possible content if I am not sure what it is that I am looking for

- [x] User should have the option of selecting 'all' in the dropdown menu when searching
- [x] result should be that they are shown all content relating to the wider issue, in this case, sleep

**Comment by iteles** [comment]
@ellemindwave I think we can close this one off?

**Comment by ellemindwave** [comment]
Yes - closing now! :)
