### ISSUE TITLE
Add “none of the above” > “add your own” to the filter options

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#128]
As a user, I want to be able to select 'none of the above' in the filtering if none of the options apply to me, and then have the option to input my own answer, so that I can let the service know what I am looking for

- [x] User should be able to select 'none of the above' in the initial search dropdown
- [x] User should be able to select ' add your own' in the initial search dropdown
- [ ] on selection of 'add your own', a free text box should appear so that the user can describe their sleep issue

@sarahwelton

**Comment by iteles** [comment]
@ellemindwave To confirm, in the sprint planning session we discussed having this box as a default in the drop-downs _without_ the 'tick to reveal' option (your first checkbox point above), can you please confirm this for us?

**Comment by ellemindwave** [comment]
@iteles Yes, that's correct. It should be there as an option in the list initially, and then the subsequent functionality for adding the input box which feeds into a spreadsheet can come later. Does that answer your question?

**Comment by sarahwelton** [comment]
Hey @shouston3 @iteles @Danwhy 

- awesome that you've got the free text box in there for users to give their suggestions - is this being entered into the same spreadsheet? Will each filter have a different column, for example?

**Comment by iteles** [comment]
@sarahwelton You should now have access to the dev (staging) spreadsheet so you can test it too! 
Yes, each type of filter has a different column 👍
