### ISSUE TITLE
Add “top content” blocks before filters

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#129]
As a service user, I want to immediately see clear and concise content so that I know I am in the right place

Before even starting to search, users will be able to see 3 content blocks / panels with relevant, trusted content so that they know they are in the right place. These might be, for example, the Expert 24 sleep algorithm, a direct link to something 'Peer to Peer' related, and Sleepio. 

- [ ] 3 equally sized content modules right above the search section
- [ ] Below the introductory copy
- [ ] Should contain short and succinct descriptions of the resources they are pointing to, and links

**Comment by ellemindwave** [comment]
Wireframe: 

![screen shot 2017-05-16 at 22 41 53](https://cloud.githubusercontent.com/assets/26304634/26129585/c07e4160-3a88-11e7-8530-bb259435d285.png)

**Comment by sarahwelton** [comment]
We're using quick links now instead of this, so closing the issue.
