### ISSUE TITLE
LDMW Heroku account

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#13]
If possible a separate Heroku account for this project would cool

(We're looking at getting hosting on the road)

**Comment by iteles** [comment]
@shouston3 Agreed. Let's set up a test gmail account and get the details for that AND for the heroku account you set up using that test gmail account into a doc on our shared google drive :+1:

Also, when you're next in the office with @tonydaly, he put together a great auto-deployment setup for Healthlocker which is worth taking a quick look over with him.

**Comment by tonydaly** [comment]
@shouston3 give me a shout if you want a demo of the pipelines, once it's all setup it's really nice.

**Comment by shouston3** [comment]
@tonydaly great, when are you in the office next?

**Comment by shouston3** [comment]
This has now being created, I just need the link to the google drive to close this, @iteles could you forward this to me

**Comment by shouston3** [comment]
This has been created and credentials added to the google drive
