### ISSUE TITLE
Figure out out how to make 'urgent support' *look* bold

### ISSUE THREAD

**Issue by iteles** [LDMW/app#149]
Although this text ('urgent support') is currently bold, it doesn't look like it!

Would be good to find a way to ensure it looks bold.

<img width="356" alt="screen shot 2017-05-11 at 11 35 11" src="https://cloud.githubusercontent.com/assets/4185328/25945200/f455ecb2-363d-11e7-8d40-6993bafc9071.png">

Adding a low priority as the text may change.

**Comment by sarahwelton** [comment]
@iteles is it a problem with the font not having enough weights? 

@indiamindwave24 FYI

**Comment by iteles** [comment]
Good question @sarahwelton, it's very possible!

**Comment by indiamindwave24** [comment]
Can the fonts be double checked. When I use the font, it appears much bolder than it does in the screenshot above https://cloud.githubusercontent.com/assets/25007700/25808027/b5a19e6a-3400-11e7-949d-41aa9092ed03.png

**Comment by iteles** [comment]
@indiamindwave24 That's what we spotted in our QA and hence the open issue.

I wasn't very clear about the question: when you use the font, do you just use 'bold' or do you use a particularly heavy font weight @indiamindwave24 ?

**Comment by indiamindwave24** [comment]
@iteles 

Normal Body (ie. if you are needing): Nunito Sans, 14px, Regular
Bold text (ie. urgent support): Nunito Sans, 14px, Bold

Is this what is currently being used?

**Comment by iteles** [comment]
Agreed for sprint 3 that we will need to redesign this and make it more prominent/change its position.

@ellemindwave Are you happy to close this issue and reference it from the new issues?

**Comment by ellemindwave** [comment]
Yes, happy to 👍
