### ISSUE TITLE
Create live, responsive landing page in the CMS

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#15]
- As a service user I want to immediately see clear and concise content so that I know I am in the right place.
- As a service user I want to immediately see what content the service has to offer so that I know it is worth further engaging with the service.

Definition of Done:
- [x] Mindwave must be able to add welcome / explanation copy 
- [x] Mindwave must be able to add copy about example content (sleep, men 18-45 as per comms) we are linking to
- [x] Mindwave must be able to add links to the relevant content on the landing page
- [x] Live page to be in line with wireframes and consistent with UI style guide
- [x] “category” filter mechanism (eg buttons, checkboxes, dropdown etc…)
- [x] Responsive across all devices and browsers (versions to be discussed, however IE9 as a minimum)

Dependencies:
- Wireframes
- Brand Identity (and any assets such as logos/fonts etc)
- UI Designs
- Content links
- Copy

**Comment by shouston3** [comment]
I will need more clarification before I can give a time estimate for this.
I can give the estimate once the wireframes (#19) has been addressed and have been given an idea of the the UI style guide.
