### ISSUE TITLE
A live, responsive content area

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#16]
- As a service user I want to be directed to trusted and relevant content so that I am confident that I can find help with my problem.

Definition of done:
- [x] Selection of introductory copy explaining what and why we are directing users to the relevant content, what they should expect, and how it might be useful to them
- [x] links to the relevant content
- [x] Mindwave must be able to add all content
- [x]  Responsive across all devices and browsers (versions to be discussed, however IE9 as a minimum)
- [x] Live page to be in line with wireframes and consistent with UI style guide

Dependencies:
- Wireframes
- UI designs / style guide
- Introductory copy
- Content

**Comment by shouston3** [comment]
Thanks @ellemindwave, I'm looking at time estimating these now.

From the "Definition of done" tasks, I think the first 3 from our perspective are the same. Essentially these will be achieved by setting up wagtail (let me know if I've misunderstood this).

I think the "Live page to be in line with wireframes and consistent with UI style guide" task would be difficult to time estimate without seeing the UI designs
