### ISSUE TITLE
Styleguide: automatically seperate components into categories

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#160]
At present the style guide dynamically generates all of the projects standard components. However, any category labels are hard coded. To improve on this, we need a function that will recognise the components categories using a folder structure.

**Comment by Cleop** [comment]
So far I have calculated how to get the full folder path and to search within subfolders, then how to divide up the received path so that it can be used only as the file name for rendering. 

However, I'm currently getting an error from the Component.View as it's erroring because the files are no longer stored under templates/component. But I'm not sure how to change this so it can expect to find them within the subfolders.

**Comment by shouston3** [comment]
You could try [setting this up](http://www.ryandaigle.com/a/recursively-list-files-in-elixir) to be able to use `FileExt.ls_r`

**Comment by Cleop** [comment]
I've got the names of the file paths which is what I think that link you shared is getting.... It's just the rendering now that is confused because it's looking for the files in the component folder but can't find them. Having not really played with the views hook-up before I don't know which file it is that I should be telling it to look for the files in their new folders.

Does that make any sense?

**Comment by Cleop** [comment]
Now I'm getting:
<img src="https://cloud.githubusercontent.com/assets/16775804/26006686/4693d4e2-3735-11e7-85d9-bd4f4961ceb5.png" width=250px />
on the `get_example_file_path` function.
This is very strange considering I can run the contents of the function successfully in iex. It's evidently something about the way it's being called that is not happy.

**Comment by shouston3** [comment]
Is there a branch I can pull down to replicate this issue @Cleop

**Comment by Cleop** [comment]
@shouston3  https://github.com/LDMW/app/tree/dynamic-styleguide

**Comment by Danwhy** [comment]
It looks like this line: https://github.com/LDMW/app/blob/dynamic-styleguide/web/views/styleguide_view.ex#L19 might be part of the problem. Path.wildcard should take the full path as the first argument, then any options as the second. Here we're passing in the file_path variable, then the full file path

**Comment by Cleop** [comment]
Thanks to @Danwhy - the issue was resolved by simply removing the piped first argument and allowing the function to draw it directly from the passed in argument.

**Comment by shouston3** [comment]
Fixed by #160
