### ISSUE TITLE
Google Analytics and Tag Manager integration

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#17]
- As a service provider, I want to track service users journeys so that we can see where they are going and how they are getting there and fix any problems 

- [x] Add relevant Google Analytics & Google Tag Manager codes to the relevant pages of the site

Dependencies:
- Define the relevant 'events' to be tracked (Sarah/Elle/Fresh Egg)
- Send DWYL the GA and GTM codes (Sarah)

**Comment by sarahwelton** [comment]
This is the Universal Analytics tracking code for this property.
To get all the benefits of Universal Analytics for this property, copy and paste this code into every web page that you want to track.

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-97311089-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by sarahwelton** [comment]
Install Google Tag Manager
Copy the code below and paste it on to every page of your website.
Paste this code as high in the <head> of the page as possible:


<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PF8GGT7');</script>




Additionally, paste this code immediately after the opening <body> tag:


<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PF8GGT7"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by sarahwelton** [comment]
- Additionally, paste this code immediately after the opening <body> tag:


<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PF8GGT7"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
