### ISSUE TITLE
Improve test coverage back up to 100%

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#176]
Currently it's just the like functionality that has brought this down to 96% 👍

**Comment by iteles** [comment]
Excellent, thanks @shouston3 ! Let's keep it here ;)
<img width="278" alt="screen shot 2017-05-18 at 22 23 30" src="https://cloud.githubusercontent.com/assets/4185328/26224050/ae906b5e-3c18-11e7-8275-e4ca98f7d40a.png">
