### ISSUE TITLE
Feedback page

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#177]
As a service user, I want to be able to quickly provide feedback on the alpha prototype so that I can influence the design and make the product as good as possible

- [x] Should link from the Alpha banner 'feedback' link
- [x] Styled according to UI (awaiting UI from @indiamindwave24 )
- [x] According to wireframes below

![screen shot 2017-05-17 at 08 41 02](https://cloud.githubusercontent.com/assets/26304634/26143708/ef0aa5c8-3add-11e7-9ff7-878b8d5f3327.png)

![screen shot 2017-05-17 at 08 41 20](https://cloud.githubusercontent.com/assets/26304634/26143413/bbf5a9b8-3adc-11e7-9cac-606fcc713a9f.png)

**Comment by indiamindwave24** [comment]
![lm_feedback_page_01](https://cloud.githubusercontent.com/assets/25007700/26242001/bef713c4-3c7e-11e7-94cc-d86ac8ae8d6d.png)

**Comment by shouston3** [comment]
@ellemindwave @indiamindwave24 @iteles 

Would you like the "what are you looking for?" and the [alpha section](http://www.londonminds.co.uk/#alpha) to be moved to this separate feedback page or are we leaving the homepage the way it is?

Sorry if this has already been clarified somewhere else.

**Comment by ellemindwave** [comment]
@shouston3 The homepage is staying the way it is, currently. 

@sarahwelton Can you confirm? 

Good question @shouston3 as it seems there are lots of places where we are now asking for feedback

**Comment by shouston3** [comment]
@ellemindwave just to confirm, are we still going to have the alpha banner at the top of the feedback page. It would link to the page you are currently on, I was thinking it would be good to have on all other views except this one

**Comment by indiamindwave24** [comment]
@shouston3 We discussed this top banner and thought it was best for consistency to keep at the top but remove the links (as you can see in my visuals above) -- is this easy to implement?

**Comment by shouston3** [comment]
That makes sense @indiamindwave24 , that should be easy enough to do 👍

**Comment by shouston3** [comment]
@indiamindwave24 @ellemindwave The "Submit feedback" button on the homepage just submits the "take part in our alpha" section.

Is that button here going to submit the whole form now?

Should we have a separate button to submit for each of the feedback sections?

**Comment by iteles** [comment]
@shouston3 I think that's an excellent question, I have some additional UX questions on this which I'm speaking to @ellemindwave at 14h00 about, will report back!

**Comment by iteles** [comment]
@indiamindwave24 @sarahwelton A few questions aside from the above:
+ This back button will fail accessibility checks because there isn't enough colour contrast. What would you like us to change this to?
<img width="134" alt="screen shot 2017-05-26 at 10 48 05" src="https://cloud.githubusercontent.com/assets/4185328/26490207/4f201288-4202-11e7-8350-3b5188d7d5fa.png">

+ Could you please also send us the proposed 'success message' for when the form is submitted?

**Comment by shouston3** [comment]
- [ ] too much spacing between each bullet point - match designs
- [ ] Give us some feedback left (aligned) and correct font (bold)
- [ ] How could we… (font)
- [ ] unbold (limit… (font)
- [ ] align bullets with “How could…”
- [ ] Any other feed… (font)
- [ ] For example (font - not bold)
- [ ] boldness configured from wagtail

**Comment by indiamindwave24** [comment]
As on style guide: secondary button on white background
<img width="389" alt="screen shot 2017-05-26 at 11 33 29 am" src="https://cloud.githubusercontent.com/assets/25007700/26491351/3157815a-4207-11e7-877a-5a0197cd818a.png">

**Comment by ellemindwave** [comment]
Please can we change the copy here to: 'Share your email address with us so that we can get you involved'

![screen shot 2017-05-26 at 11 41 11](https://cloud.githubusercontent.com/assets/26304634/26491632/551aac1a-4208-11e7-8cca-f1c6f3041be5.png)

**Comment by indiamindwave24** [comment]
RE: stark colour contrast -- removed blue background
