### ISSUE TITLE
Configuring Heroku servers

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#18]
From the way we will be hosting the two servers with Heroku we will have the following pages:

+ ldmw-cms.herokuapp.com/ - for previewing changes to cms made by admin (may eventually not need this)
+ ldmw-cms.herokuapp.com/admin - for changing content of main app
+ ldmw-app.herokuapp.com/ - main app

When we host the site on ldmw.com/ (for instance) how should we manage these endpoints? Perhaps something like this:

+ ldmw.com/admin -> ldmw-cms.herokuapp.com/admin
+ ldmw.com/preview -> ldmw-cms.herokuapp.com/
+ ldmw.com/ -> ldmw-app.herokuapp.com/

I feel a little unsure of how best to go about configuring the one domain to serve different heroku apps depending on the endpoint.

@nelsonic I'd like to hear your thoughts on this.
@Danwhy Is this the problem you were describing to me on Thursday? If so, have I been clear/missed anything?

**Comment by nelsonic** [comment]
@shouston3 thanks for asking this question to get clarification. 👍 
I'm in favour of using a ***subdomain*** for the **application** such that the _content_ is on the main domain (_e.g: https://ldmw.io ..._) and the application is on https://app.ldmw.io

![ldmw-application-architecture-diagram-2](https://cloud.githubusercontent.com/assets/194400/25383411/e539b36c-29b3-11e7-84e1-5637cac59574.png)
(_diagram updated with this suggestion_)

**Comment by shouston3** [comment]
Great clear now, closing
