### ISSUE TITLE
Devices for Sprint 3

### ISSUE THREAD

**Issue by iteles** [LDMW/app#181]
@indiamindwave24 Can I confirm that the devices for sprint 3 are Chrome on Mac and an iPad?

**Comment by indiamindwave24** [comment]
@ellemindwave can you confirm?

**Comment by ellemindwave** [comment]
As in, these are the particular devices/browsers that we are improving responsiveness for in this sprint? (aside from mobile-everything being best in the first instance)

If that's the case, then yes this is a good start 👍

**Comment by iteles** [comment]
Linked to #189 

Thanks for confirming @ellemindwave 👍
