### ISSUE TITLE
Alpha banner text needs to be bigger

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#182]
Taken from issue: https://github.com/LDMW/app/issues/52#issuecomment-302009473

<img width="789" alt="screen shot 2017-05-26 at 11 09 36" src="https://cloud.githubusercontent.com/assets/4185328/26490584/dd2a5b3c-4203-11e7-8493-1ecdff6fb0d8.png">

**Comment by iteles** [comment]
@indiamindwave24 This is 12px as per the designs, but we'll bump it to 14px to see if that looks better 👍 

This is a good idea though, we've bumped all the other 12px text up a size or two to ensure accessibility across the site already.

**Comment by indiamindwave24** [comment]
apologies, thats must have been an error on my part - no text below 14px please :D
