### ISSUE TITLE
Production processes

### ISSUE THREAD

**Issue by iteles** [LDMW/app#185]
We need to establish our processes and scripts for migrating new features to production.

Linked to #99

**Comment by shouston3** [comment]
These are the current planned steps for performing this process:
APP
1. Backup app database (using: `pg_dump dbname > outfile`)
(can be restored with `psql dbname < infile`)
push this data to github
2. deploy certain commit (potentially as argument)
CMS
1. dump data into backupdata branch (ensure natural keys flags)
   push backup to github cms repo
2. deploy cms master branch
   run migrations
3. run ecto.migrate

**Comment by shouston3** [comment]
We are planning to have a separate repo just for our backup data
Since the only thing changing here will be the backup data, we don't want it to clash with our code changes and cause conflicts which could clash with our deployment script

**Comment by shouston3** [comment]
Deployment script has been setup and instructions have been added to the readme
@iteles Reassign if there's more to do

**Comment by iteles** [comment]
@shouston3 Tested today on our first deployment 'run' and everything appears to be working well 👍
