### ISSUE TITLE
'Success' message styling

### ISSUE THREAD

**Issue by indiamindwave24** [LDMW/app#187]
Success message should appear as below:

- [x] Success message replaces/appears in text box
- [x] Tick should be in top right corner
<img width="486" alt="899884e0-3401-11e7-821f-5378e58f81c3" src="https://cloud.githubusercontent.com/assets/25007700/26154717/85209836-3b08-11e7-8289-b51309887402.png">

**Comment by iteles** [comment]
Current status:
<img width="309" alt="screen shot 2017-05-17 at 14 03 01" src="https://cloud.githubusercontent.com/assets/4185328/26154986/942ef8a8-3b09-11e7-8a71-ef687703e55c.png">

**Comment by shouston3** [comment]
Implemented in #234

**Comment by indiamindwave24** [comment]
fab! 👍
