### ISSUE TITLE
Responsiveness tweaks for Mac Chrome and iPad/tablet

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#189]
As a user, I want the digital service to look just as good on any device and browser that I view it on, so that I can trust that it is a reputable service and I feel confident using it

- [ ] Spacing / text / images should all scale correctly
- [ ] According to UI from @indiamindwave24 
- [ ] According to wireframes from @sarahwelton 
- [ ] Currently prioritising Mac Chrome and Ipad/Tablet (IE not currently a priority)

**Comment by iteles** [comment]
We allocated a block of 4 hours for tweaks in this sprint and will revisit what can be done once we have the designs 👍

**Comment by indiamindwave24** [comment]
There is little difference for desktop - please see Zelpin for desktop designs however following updated styling shown on the mobile styleguide (already implemented)

**Comment by iteles** [comment]
@indiamindwave24 @sarahwelton The desktop designs were last updated 24 days ago and we've been implementing this as a guide as we go.

Is there anything in particular that you think is not working responsively in the way you envisaged?

**Comment by indiamindwave24** [comment]
the logo
<img width="2396" alt="screen shot 2017-05-26 at 11 36 32 am" src="https://cloud.githubusercontent.com/assets/25007700/26491469/a6c13a1c-4207-11e7-892f-83c944d51d05.png">

The get support page:
<img width="1289" alt="screen shot 2017-05-26 at 11 37 57 am" src="https://cloud.githubusercontent.com/assets/25007700/26491512/dc2d85e8-4207-11e7-8d3c-00c51f6b301f.png">

Coming soon page icon
<img width="989" alt="screen shot 2017-05-26 at 11 40 09 am" src="https://cloud.githubusercontent.com/assets/25007700/26491579/1f5494b0-4208-11e7-8233-37d971ad5e5c.png">


Tags split acrossc lines
<img width="1068" alt="screen shot 2017-05-26 at 11 39 06 am" src="https://cloud.githubusercontent.com/assets/25007700/26491536/f92377f2-4207-11e7-8116-7108c3af0790.png">

@sarahwelton -- let me know if you have come across anything else

**Comment by iteles** [comment]
@indiamindwave24 We're looking at the website on standard laptop and desktop monitor sizes.

It's probably a good question - do we want to be catering for 4k mega monitors like the one you use? This isn't something we've tested until now.

**Comment by indiamindwave24** [comment]
It would be good to test on this if possible :)
