### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#19]
@sarahwelton 

For the wireframes which of the 4 options for the landing page wireframes would you like us to work towards?

For example in this one:
![download](https://cloud.githubusercontent.com/assets/15983736/25007668/1e8889ae-2059-11e7-9f37-ce3ad3526b51.jpg)

Would it just be the introduction at the top which you would like the content to be manageable with the cms?
Would you also like the "what are you struggling with?"/"Get involved" portions also to be accessible?
Or each piece of text content on the page?
Were you thinking of having other sections on the landing page too?

**Comment by ellemindwave** [comment]
@shouston3 Hi Sam, as Sarah isn't in today, I am jumping in. 

Sarah asks:
It was mentioned by @nelsonic that Wagtail allows for tagging of content and then automatically displays a set of 'buttons' that show the user the categories that are available. 
If that's the case then we should start with that as that means a lot of the work will be done by Wagtail?

If this is the case, then based on the high level wireframe sketches on the wall of the studio, @sarahwelton would like number 3 to be the wireframe used (below).

You should also work on the assumption that the whole site is to be as content manageable as possible please, so all text and content should be able to be edited from the CMS.

![image uploaded from ios 8](https://cloud.githubusercontent.com/assets/26304634/25334880/8466e47c-28e8-11e7-9a4b-a13292f38a88.jpg)

**Comment by Cleop** [comment]
Designs now received: https://app.zeplin.io/project/59027357309e7a3841c6bf47/screen/5902737f5188690d46036e24
