### ISSUE TITLE
Crisis banner relocation and redesign 

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#190]
As a service user, I want to know that should I need urgent help, I will be directed to the appropriate place to receive adequate support so that my situation doesn’t become worse

- [x] Crisis banner to be made more prominent and obvious
- [x] To be positioned on the page according to the wireframes ( @sarahwelton )
- [x] Styled according to UI ( @indiamindwave24 )
- [x] To link to the crisis page

(This issue replaces issue no #149 )

**Comment by indiamindwave24** [comment]
<img width="320" alt="screen shot 2017-05-18 at 4 48 00 pm" src="https://cloud.githubusercontent.com/assets/25007700/26211284/25331f42-3bea-11e7-82d9-98848ea68569.png">

- [ ] Using orange banner
- [ ] Repositioning below sleep assessment banner
- [ ] link text follows style guide as link on colorued background (For GDS)

**Comment by indiamindwave24** [comment]
<img width="320" alt="screen shot 2017-05-18 at 4 48 00 pm" src="https://cloud.githubusercontent.com/assets/25007700/26211284/25331f42-3bea-11e7-82d9-98848ea68569.png">

- [ ] Using orange banner
- [ ] Repositioning below sleep assessment banner
- [ ] link text follows style guide as link on coloured background (For GDS)

**Comment by iteles** [comment]
@ellemindwave We've made the link blue because the white on orange fails accessibility checks. Other than that, this is ready to test. 👍

**Comment by indiamindwave24** [comment]
Looks good 🎉
