### ISSUE TITLE
Feedback input box when you click like/dislike

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#191]
As a user, I want to be able to give feedback if I have used a resource before, so that I can let the service know how useful it was to me, and any additional feedback

- [x] Input box to reveal on interaction with the thumbs up / thumbs down
- [x] Input box to be a free text box
- [x] Input box entries to feed into a Google spreadsheet
- [x] According to wireframes ( @sarahwelton )
- [x] Styled according to the UI ( @indiamindwave24 )

**Comment by iteles** [comment]
We also agreed that the text for this input box would be static and not editable in the CMS 👍

**Comment by indiamindwave24** [comment]
**Thumbs up**

Can we please change the thumbs up icons, again? Seeing them on the site, I think it would work better as:

_Unselected:_ Dark blue
_Hover:_ Orange
_Selected:_ Orange

UI will follow the style guide for text box. Let me know if you have any UI queries following the wireframes :)

**Comment by iteles** [comment]
@ellemindwave @sarahwelton This is ready to test. 
You'll see a flash when you first click - this is due to not using Javascript. The functionality is as requested 👍

**Comment by indiamindwave24** [comment]
Can you please make sure everything is tested internally across devices before adding a please test label. 

The text box does not fill the width of the screen on mobile. This needs to be fixed 

Why is JavaScript not being used? For GDS we only need to have an ALTERNATIVE if JavaScript is not enabled. 

The screen refreshes at the moment, flashes the top of the homepage and then navigates down the page but you cannot see the thumbs up you have just input 

(iPhone 6 safari)

**Comment by sarahwelton** [comment]
@iteles Also - another question - at the moment you cannot "un-like" or "un-dislike" (eg remove the selection you have made). Aware that this was not explicitly specified, but would assume that this would be the normal behaviour (as per Facebook, Reddit etc). Is this a bug?

**Comment by sarahwelton** [comment]
- and are these answers entering into the same spreadsheet?

**Comment by shouston3** [comment]
@sarahwelton The un-like functionality issue has been opened [here](https://github.com/LDMW/app/issues/243)

**Comment by shouston3** [comment]
@sarahwelton The feedback is going through on `heroku-app-staging`, but only to our development spreadsheet [here](https://docs.google.com/spreadsheets/d/1VfzvK-s2a8zxI6j5zLMrLZMmEqhceTjklcybdtSAb0Q/edit#gid=0) which @Danwhy and I have been using for testing.

The feedback should be going through properly once we deploy to the main site

**Comment by sarahwelton** [comment]
@shouston3 Okay thanks! So I will test when its on the main site as I can't see the spreadsheet entries yet.

**Comment by shouston3** [comment]
Granted to the three of you, you should be able to access it [here](https://docs.google.com/spreadsheets/d/1VfzvK-s2a8zxI6j5zLMrLZMmEqhceTjklcybdtSAb0Q/edit#gid=0)
