### ISSUE TITLE
Styleguide: stop duplicate categories appearing

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#193]
At present the standard components style guide lists the component category, however it does this for each component within that category meaning you will end up with lots of duplicates.

To improve this we need a function that will check if a category has already been listed to ensure it is only displayed once.

**Comment by Cleop** [comment]
The proposed data structure to handle this functionality: 
<img src="https://cloud.githubusercontent.com/assets/16775804/26198106/b58e092c-3bbc-11e7-84c6-2c428c19c1a6.png" width=500px />

**Comment by shouston3** [comment]
I think it may be better to keep keys lowercase and utilize [`String.capitalize`](https://hexdocs.pm/elixir/String.html#capitalize/1) if you need them as capitals

**Comment by Cleop** [comment]
Initial solution completed in 3.5 hours. Revising time estimate for refactoring.

**Comment by shouston3** [comment]
Closed by #199
