### ISSUE TITLE
13/4 Call

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#2]
**Note: from memory, should have made notes (next time)**

The main points from the conversation were:

### Sprint planning

We will be working in a more agile way with everyone getting involved with time estimating each feature that will be built.

Fast iterations on each new feature.

### Why Wagtail?

Because it is a cms which has already been integrated in parts of the nhs, but there is no real tie to it (I'm actually quite happy to go with it though).

### Project clarity

There will be much more of a plan for next week during the project planning phase

### Wireframes

![download](https://cloud.githubusercontent.com/assets/15983736/25007668/1e8889ae-2059-11e7-9f37-ce3ad3526b51.jpg)
![download-1](https://cloud.githubusercontent.com/assets/15983736/25007669/1fd1af84-2059-11e7-8b3e-94868cafe8a6.jpg)
![download-2](https://cloud.githubusercontent.com/assets/15983736/25007671/20e802ce-2059-11e7-8e25-b55564e96320.jpg)
![download-3](https://cloud.githubusercontent.com/assets/15983736/25007673/22268aac-2059-11e7-93c8-26ede2fd2b72.jpg)

**Comment by iteles** [comment]
We have evolved slightly from this point 😊 
Thanks for the notes Sam! Closing and we can have this as a reference.
