### ISSUE TITLE
Consider adding in sass

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#205]
We should perhaps look to modularise our css in some way as our one css file: [`web/static/css/app.css`](https://github.com/LDMW/app/blob/master/web/static/css/app.css) is growing.

Do you think we should look at doing this some time soon @Danwhy @nelsonic @iteles ?

**Comment by Danwhy** [comment]
We can separate our css file into as many as we want already, brunch will bundle them all together

**Comment by shouston3** [comment]
^^ better idea

**Comment by shouston3** [comment]
We can look at: https://github.com/sergiotapia/phoenix-sass-example, found in this answer: http://stackoverflow.com/questions/31978664/how-to-use-sass-scss-with-phoenix-framework

**Comment by shouston3** [comment]
Our css is maintainable enough without sass, closing until this becomes an issue

**Comment by shouston3** [comment]
[Our css is currently 515 lines](https://github.com/LDMW/app/blob/master/web/static/css/app.css)

It was originally separated out with `/* commented headers */` for each section, but that convention has stopped.

We are now just appending new css to the bottom of the file (not very sustainable).

I implemented sass into a phoenix project over the weekend and it was quite easy and organises the css a lot better. I thought it would be quick to implement. (I have not spent very much time making much of a refactor as of yet)

I'm ok to not implement this and I'll close this issue, but I think it organises the code better.

Let me know your thoughts @nelsonic

**Comment by nelsonic** [comment]
@shouston3 is using `SASS` going to reduce the number of lines or complexity?
https://github.com/LDMW/app/blob/777e1bfbb35b6125c577c5eef54170ee146cc466/web/static/css/app.css it seams pretty readable and most of the classes are single-purpose & composable.

**Comment by shouston3** [comment]
`SASS` won't reduce the number of lines of complexity, closing

**Comment by nelsonic** [comment]
@shouston3 I'm not _against_ using `SASS` if you think it will _simplify_ the project.

**Comment by shouston3** [comment]
I actually think in retrospect that my pr was a little premature, our css files aren't that complicated (yet).

I just got a little keen with discovering how well sass plays with brunch on the weekend and thought that there was no real downside of having it
