### ISSUE TITLE
Update copy in alpha block on homepage

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#214]
Please can the copy on the alpha box have no more latin, and read as follows : 

'The “alpha” phase is all about testing ideas and gathering feedback from the people that will be using the service.

Everything you see now can change based on what you think works and doesn’t work, so please let us know!

Any feedback you give us will be used to improve the content and functionality of the service, as well as the way the service looks'

**Comment by shouston3** [comment]
@ellemindwave should be changed
