### ISSUE TITLE
De-list from Google

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#222]
The site shouldn't currently appear in a Google search, please de-list.

This is so that we can have a controlled group of people being directed to the site to test and get feedback whilst it is in the alpha phase.

**Comment by Danwhy** [comment]
[robots.txt](https://github.com/LDMW/app/blob/master/web/static/assets/robots.txt) should stop Google indexing the site next time it tries to crawl it.
In the meantime, I have requested that Google temporarily remove it from search results:
<img width="1058" alt="screen shot 2017-05-24 at 13 37 48" src="https://cloud.githubusercontent.com/assets/8939909/26403458/40cc877a-4086-11e7-8b02-d34599235ab5.png">

**Comment by ellemindwave** [comment]
Great, thanks @Danwhy
