### ISSUE TITLE
Alert when someone likes/dislikes content

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#229]
Currently a bar appears at the top of the page when you like/dislike content. See below. 

@sarahwelton @indiamindwave24 what do you think would be the best option here?
I would think it would be better to not have that happen at all, as the very fact they can see the numbers changing next to the thumbs should be enough to tell them their vote has counted?

![image uploaded from ios 9](https://cloud.githubusercontent.com/assets/26304634/26440241/5acdff76-4123-11e7-8633-9e7778c9a113.jpg)

**Comment by shouston3** [comment]
@ellemindwave we can just remove this flash message.

The user should be able to see their highlighted like or dislike

**Comment by ellemindwave** [comment]
Great, that sounds like a good option 👍

**Comment by shouston3** [comment]
Added in #229

**Comment by indiamindwave24** [comment]
Sticky to top of (scrolled screen)
![Uploading 65499e3e-4532-11e7-9ef5-561698574dee.png…]()

**Comment by indiamindwave24** [comment]
Sticky to top of (scrolled screen) @shouston3 
<img width="407" alt="65499e3e-4532-11e7-9ef5-561698574dee" src="https://cloud.githubusercontent.com/assets/25007700/26583764/62d0d6b6-453e-11e7-87db-2a0613759318.png">

**Comment by iteles** [comment]
@indiamindwave24 We've removed this flash message entirely as requested by @ellemindwave [above](https://github.com/LDMW/app/issues/229#issuecomment-3039769900.

If we _do_ want this after all, I think it's actually good to reopen issue #249 and keep it separate for the next sprint! 😊

**Comment by iteles** [comment]
@ellemindwave As agreed in our sprint planning, please test this issue for the _removal_ of the banner and we'll deal with adding it back in in issue #249 in sprint 4?
