### ISSUE TITLE
Temporarily hide/deactivate Ts&Cs and Contact Us links

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#230]
As a user, I want every link that I click on to be directed to somewhere useful, so that I trust the credibility of the site. 

Please can we temporarily hide the Ts&Cs and Contact links from the page footer on the live site? Or at least, make sure they have no link attached to them (the currently go to a google search of Ts&Cs and Contact)

Thanks!

**Comment by shouston3** [comment]
I've removed the content from the footer. @ellemindwave You can add in whatever content you would like in the footer in the cms

**Comment by ellemindwave** [comment]
Ah - perfect. Thanks very much @shouston3 👍
