### ISSUE TITLE
Update filter questions copy

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#237]
As a user, I want the wording of the questions that allow me to filter content and make it relevant to be easy to understand and intuitive, so that I can filter easy and quickly get to suitable content. 

@sarahwelton will be confirming what the copy for these questions and their answers should be asap
@iteles @shouston3 @Danwhy am I right in thinking that these questions are as of yet not able to be changed in the CMS? (due to it being quicker for this sprint)

**Comment by sarahwelton** [comment]
@Danwhy @ellemindwave @iteles @shouston3 @katerobb 

1) - Are you currently experiencing any of the following?
2) - Is anything in particular affecting your sleep?
3) - What type of support are you looking for?

**Comment by sarahwelton** [comment]
@ellemindwave @iteles @Danwhy @shouston3 @katerobb 

1 
- Are you currently experiencing any of the following?

2
- Do you know of anything that might be affecting your sleep?

3 
- What type of support are you looking for?
