### ISSUE TITLE
All of the static content on the homepage is editable with the cms

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#238]
As an admin user, I would like to have control over the content which will be displayed on the application so that I can keep the application up to date and I don't have to keep asking the development team every time a change needs to be made.

### Acceptance Criteria
+ [x] The following content should be editable:
  - [x] Alpha prototype banner
  + [x] Filter question labels
  - [x] "Take our clinically approved sleep self-assessment"
  - [x] "If you are needing urgent support please "click here"

**Comment by iteles** [comment]
Lowest priority in sprint 5 👍

**Comment by sarahwelton** [comment]
I can't change the styling on the crisis banner (I need to add more explanation into it but don't want it all to be a link, just the CTA... I know we amended the copy to be all a link before but assumed that we could amend in the CMS)
