### ISSUE TITLE
Unlike or un-dislike

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#243]
As a user who has liked or disliked a resource, I would like to be able to undo my decision of liking or disliking, so that if I have clicked on one of these by mistake or if I change my mind, I can correct this feedback I am providing.

### Acceptance Criteria
+ [x] Once a like button has been clicked (and gone orange), a user can click this again 
  + [x] The number of likes will decrement by 1
  + [x] The like icon will go back to its original blue outline (inactive state)
+ [x] Once a dislike button has been clicked (and gone orange), a user can click this again 
  + [x] The number of dislikes will decrement by 1
  + [x] The like icon will go back to its original blue outline (inactive state)

**Comment by iteles** [comment]
Not in original sprint 3 scope.
