### ISSUE TITLE
Feedback loop spike

### ISSUE THREAD

**Issue by iteles** [LDMW/app#244]
It was agreed in our previous sprint planning that the feedback loop https://github.com/LDMW/app/issues/131 was not a priority for Sprint 3 but Glen showed particular interest in understanding how big this piece of work could be and we would need to carry out a spike to better understand it.

### Acceptance Criteria
+ [x] Estimate created for #131 ahead of Sprint 5
+ [x] Comments added in this issue with results of spike

**Comment by Danwhy** [comment]
When a user clicks a link on skyscanner to purchase a ticket, the linked site opens in a new tab
<img width="586" alt="screen shot 2017-06-05 at 14 22 30" src="https://cloud.githubusercontent.com/assets/8939909/26785467/71f67d60-49fa-11e7-98d1-8d81cab7a98e.png">

On the original tab, where the user clicked the button, a blue box asking how the booking experience on the linked site was.

<img width="584" alt="screen shot 2017-06-05 at 14 14 56" src="https://cloud.githubusercontent.com/assets/8939909/26785341/c523b4f4-49f9-11e7-9712-ba1240816eaf.png">

It looks like skyscanner are simply doing this with javascript when a link is clicked on, and as the original page stays open, there's no need to attach a cookie to determine where it was the user went.
We could do the same, displaying the feedback box when a user visits on of the sites. If we want to remember which sites the user has visited, we could use a cookie/local storage, however if we do this, we may need to [add a cookie notice](http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm)

**Comment by iteles** [comment]
@Danwhy Thanks for this! Please could you spike both options and provide a time estimate for the implementation of each along with a list of their limitations so that our PO can make a decision for the upcoming sprint?

**Comment by Danwhy** [comment]
### New tab with javascript/server refresh - 2 hrs
 We just open the site in a new tab when the user clicks the url, then display the request for feedback, whether that's the feedback box we're currently using or a new design.

Pros 
* Keeps the site open, encouraging the user to come back.

Cons
* Does not persist through sessions, meaning once the user closes the site, if they didn't leave feedback the first time, we won't know which sites they visited.

### Cookies - 6 hrs
We give the user a cookie when they click on a link, so the next time they return to the site, we know what sites they visited and can ask for feedback about them.

  Pros 
* Can persist across sessions.

Cons
* Relies on the user to come back to the site at a later date and remember to give feedback.
* Would probably count as tracking users via cookies, so we'd have to add a cookie policy, and notice: http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm

(Time estimates are for functionality only, any implementations of new designs not included)

**Comment by iteles** [comment]
Done and will be captured in  #131
