### ISSUE TITLE
Block Mindwave and dwyl IP address from GTM

### ISSUE THREAD

**Issue by iteles** [LDMW/app#261]
Fresh Egg have suggested that the Mindwave and dwyl IP addresses are blocked from GTM.

This implies having static IP addresses. I can test this for dwyl but @ellemindwave, can you find out if Mindwave has one?

_Note:_ Standard home wifi networks do not have static IP addresses so when anyone on the Mindwave or dwyl teams works remotely, it will have no effect.

**Comment by ellemindwave** [comment]
@Danwhy @iteles 

It looks like we will need to engage with our ISP to get a static IP allocated, as we don't currently have one. 
Unless you have any ideas / advice on other ways to get round this?

**Comment by ellemindwave** [comment]
@Danwhy @iteles 

Tom has told me that this is the current IP address of our router:
80.229.187.108

This isn't necessarily static as we didn't specifically request a static IP address on setting it up, but it would be a good start to block this, and then if it changes we can update...?
In the meantime I have added to my list to get in touch with our ISP to get a static address.

**Comment by Danwhy** [comment]
@ellemindwave @sarahwelton I can't add a filter to the Google Analytics, apparently I need to have 'edit' access to the account, as well as the property
<img width="354" alt="screen shot 2017-06-05 at 16 12 51" src="https://cloud.githubusercontent.com/assets/8939909/26789950/dea8ab18-4a09-11e7-9110-f419afda98d7.png">

**Comment by ellemindwave** [comment]
@Danwhy as far as I can see, you have edit access?

![screen shot 2017-06-05 at 16 17 21](https://cloud.githubusercontent.com/assets/26304634/26790139/92a36e14-4a0a-11e7-9bf6-f0694b18f0d4.png)

**Comment by Danwhy** [comment]
Is that definitely for the Account level? There should be three types of user management: http://www.ganotes.com/cant-add-a-filter-to-google-analytics/

**Comment by ellemindwave** [comment]
@Danwhy Yes, I have just gone into the Account level and you are on 'publish' which is the highest rank of admin as far as I can see?

![screen shot 2017-06-07 at 13 27 36](https://user-images.githubusercontent.com/26304634/26878361-1fa5b59e-4b85-11e7-9c63-3940c39a66a6.png)

**Comment by Danwhy** [comment]
I've added filters for all relevant IP addresses. I'll make sure to check it regularly to make sure the IP addresses don't change:
<img width="682" alt="screen shot 2017-06-09 at 10 41 13" src="https://user-images.githubusercontent.com/8939909/26970198-65a5b9fa-4d00-11e7-802f-a252f8213f02.png">
