### ISSUE TITLE
Display top 5 results + 'Show More' button for homepage resources

### ISSUE THREAD

**Issue by iteles** [LDMW/app#262]
As a user, I want to only see the top 5 weighted resources on the homepage by default so that I don't have to scroll through EVERYTHING when there are lots of resources

### Acceptance Criteria
+ [x] I see five resources
+ [x] Show more button styled as a primary button (as the 'Filter' button)
+ [x] When I click 'Show more' button, I see _all_ the resources

**Comment by sarahwelton** [comment]
@katerobb @indiamindwave24 @ellemindwave 

5 is still quite long on my smaller laptop. What do you all think? It seems like a more reasonable number than 3, but not sure if its still too much... (I personally don't mind it but a couple of users have mentioned in testing that it just goes on and on...)

**Comment by indiamindwave24** [comment]
@sarahwelton Perhaps we do 3 and test... agree it takes a long time to get to bottom panel which we need for feedback
( @iteles is is possible to do 3 on mobile, 5 on desktop? )

**Comment by iteles** [comment]
Let's try three for the initial user tests then and add a separate issue for having varying numbers on mobile and desktop so we can think about possible implementations for that 👍
