### ISSUE TITLE
Share icon feedback

### ISSUE THREAD

**Issue by iteles** [LDMW/app#264]
As a user, I need something to happen when I click the share icon so that I don't click indefinitely without feedback to know if anything is happening.

### Acceptance criteria
+ [ ] When a user clicks on the share icon, they see a little message to say it's coming soon (UI to be confirmed by India - possibly like the feedback users get when they submit an email)
+ [ ] Feedback box placement to be confirmed by @indiamindwave24

**Comment by ellemindwave** [comment]
@indiamindwave24 @iteles This issue is no longer relevant as we are going to get rid of the share icon
