### ISSUE TITLE
Embeddable youtube video link

### ISSUE THREAD

**Issue by iteles** [LDMW/app#265]
As an admin, I would like users to see youtube video links I input as embedded videos in the resources so they don't have to click away from the site.

### Acceptance Criteria
+ [x] Site admin is able to add a video link, linked to a specific resource
+ [x] Video shows as embedded at the bottom of the relevant resource card

Note: Agreed this is only a requirement for _youtube_ video links for now.

**Comment by sarahwelton** [comment]
@danwhy - does this work on the live site? I have tried to add a video but its not showing up...

**Comment by shouston3** [comment]
@sarahwelton It should work for edits made here: https://ldmw-cms-staging.herokuapp.com/admin
To the staging site: https://ldmw-app-staging.herokuapp.com/

**Comment by sarahwelton** [comment]
Ahhh okay - I don't think I've seen the staging CMS yet! Thank you.
