### ISSUE TITLE
Images spike

### ISSUE THREAD

**Issue by iteles** [LDMW/app#266]
In order to better estimate #31  #112, we need to carry out a spike on this functionality

**For consideration: How do we manage image dimensions through the CMS and pull those through to the front end?**

### Acceptance Criteria
+ [x] Estimate created for #31 and #112 ahead of Sprint 5
+ [x] Comments added in this issue with results of spike

**Comment by Danwhy** [comment]
Based on [this guide](https://wagtail.io/blog/amazon-s3-for-media-files/), setting the image uploads to S3 should be quite straightforward, it just involves some configuration on the wagtail end, as well as setting up the S3 bucket, giving it the correct permissions etc. 
It seems straightforward, but there are quite a few steps, and AWS is notorious for causing unforeseen issues, so I would put aside __1 day__ for this task.

In regard to managing image dimensions, we can put a limit on image sizes on the front end, but it's probably best just to upload the image in the desired size.

**Comment by shouston3** [comment]
We've made a start on this in #349 and implemented it in #351

**Comment by iteles** [comment]
Thanks! Completed 👍 Sprint 5 will contain the image upload issues that follow on from this.
