### ISSUE TITLE
Ensure that feedback form works if only a few questions are answered

### ISSUE THREAD

**Issue by iteles** [LDMW/app#267]
As a user, I want to be able to fill out as many questions on the feedback form as I like and not get an internal server error when I only fill in one question so that I trust the credibility of the service and don't feel under pressure to provide more information than I feel comfortable providing

- [x] Users can hit submit after having filled out one or more questions on the feedback page
- [x] Internal error message should not appear

**Comment by shouston3** [comment]
I think the flash message here may be wrong, will address that in #295

But this issue should be addressed

**Comment by iteles** [comment]
@shouston3 I think we briefly spoke about this last week, the key things is that **all questions are optional**.

This means that **if a user fills in _one_ field and presses submit**, the form should submit without any problems and record that one answer in the db and spreadsheet.
  + This is what this issue's bug was originally about - when a user submitted just one answer, we used to get a 500 error
  + Currently it's giving an email validation error which is what I think you're referring to above, but it shouldn't give any error at all, it should submit the form.

**Comment by iteles** [comment]
Could you please also update the time estimate here to how long the issue took

**Comment by shouston3** [comment]
@iteles Could I just clarify something about the feedback submission.
If a user enters any piece of data other than an email address we should send it to the spreadsheet
If a user enters only an invalid email address we should tell them the email address is invalid
What should we do if a user enters data in some of the form fields, then enters an invalid email address?
Should we not send anything to the spreadsheet and flash an invalid email error?

**Comment by iteles** [comment]
Working as expected, thanks! 🎉
