### ISSUE TITLE
Creating separate views in GTM

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#269]
As a service provider, I want to have separate views for different purposes in GTM, so that I am able to track all the data from London Minds in a clear and ordered way

From Fresh Egg: 

'As standard, you require an "All website data"(this serves as a back up and no filters should be applied to this) a "Test" (for testing any changes/updates) and a "Reporting" view which will be used for analysing the data. You should also add IP and Spam Filters so that the data isn't corrupted.

- [x] - 'All website data' view
- [x] - 'Test' view
- [x] - 'Reporting' view
- [ ] - Block IP address so that we aren't corrupting the data (is this possible yet?)

Please can I have a time estimate on this?

**Comment by Danwhy** [comment]
@ellemindwave If you know the IP addresses/subnet that you want to block we can do this

**Comment by iteles** [comment]
@ellemindwave @Danwhy I'd created a separate issue for this in the sprint planning session #261
