### ISSUE TITLE
track site using Hotjar

### ISSUE THREAD

**Issue by katerobb** [LDMW/app#270]
Have any of you used Hotjar to track users? I've got a 14 day free trail. Would it be possible to add in their tracking code and see how good it is and if we'd want to purchase it going forward?
@iteles 

![screen shot 2017-05-31 at 15 29 17]
![screen shot 2017-05-31 at 15 29 17](https://cloud.githubusercontent.com/assets/28757909/26638083/2a882544-4619-11e7-96ce-e812b7cda7c6.png)

**Comment by iteles** [comment]
@katerobb We've never used it but happy to give it a shot.

If the trials are 14 days, worth only activating once we know we'll have users (either testing or organic traffic) as for now we've delisted from google #222 so no one can find the site.

@ellemindwave Could you let us know what the priority is on this and most importantly if there is a user testing date we want to trial this before?
For now I believe the decision is to go with the free GTM for alpha, but might be a good consideration for beta.
