### ISSUE TITLE
Designs for error messages

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#279]
As a user, I want to be alerted to the fact that an action I have tried to make is not ready yet or not possible, so that I am informed and understand why it has not worked. 

Acceptance Criteria
- [ ] Error messages to appear at points agreed in sprint planning
- [ ] Error messages to be styled according to style guide and @indiamindwave24 's comments below

![screen shot 2017-06-02 at 08 03 47](https://cloud.githubusercontent.com/assets/15983736/26714608/23a33c6c-476a-11e7-918e-4d4b7d1b3228.png)
@indiamindwave24 This is what I've initially gone for.
@iteles commented that it may be bad UX to have a cross on the top right (people may try to close the popup).
What should this look like?

**Comment by iteles** [comment]
'misleading' rather than bad :wink:

**Comment by indiamindwave24** [comment]
Let's use an exclamation mark instead 😀 
<img width="677" alt="screen shot 2017-06-02 at 10 45 13 am" src="https://cloud.githubusercontent.com/assets/25007700/26720560/a90fe40c-4780-11e7-9b96-7108ab6e0407.png">

Please make sure that the colours correspond with the style guide

**Comment by shouston3** [comment]
Thanks for these designs @indiamindwave24
