### ISSUE TITLE
Add latest style guide to the documentation in this repo

### ISSUE THREAD

**Issue by iteles** [LDMW/app#282]
For quick reference, it would be good to add the latest version of @indiamindwave24's styleguide to this repository so there is no doubt over which styles to use.

@indiamindwave24 Do you need to make any updates to the original ahead of us doing this?

Thanks!

**Comment by indiamindwave24** [comment]
Yes --- will update now

**Comment by indiamindwave24** [comment]
@iteles If you notice anything missing let me now - think this is in line with where we are 😄 
![style_guide_mobile_04](https://cloud.githubusercontent.com/assets/25007700/26722692/f7418420-4788-11e7-95d9-94ea9b7643da.png)

**Comment by iteles** [comment]
@indiamindwave24 Is this updated on Zeplin or just your local machine?

**Comment by indiamindwave24** [comment]
I just uploaded onto here, not Zeplin as Dan said they are not using Zeplin @iteles

**Comment by shouston3** [comment]
@indiamindwave24 could you upload it to Zeplin please. Zeplin would be better for us than github

**Comment by iteles** [comment]
To explain @indiamindwave24, we don't tend to use zeplin but having it a single place where you can keep it continuously up to date without having to remember to copy paste into issues constantly would be great

**Comment by indiamindwave24** [comment]
Ok, it is on Zeplin now 👍

**Comment by iteles** [comment]
@shouston3 Sorry to be picky but can we make it a link so people don't have to highlight/copy-paste and enter?

Also worth a note to say that if access is required, please ask the project maintainers!

<img width="204" alt="screen shot 2017-06-09 at 22 20 42" src="https://user-images.githubusercontent.com/4185328/26994941-06da02d4-4d62-11e7-8faf-b2cb4aac9796.png">

**Comment by iteles** [comment]
Merged #355 and this can now be closed 👍
