### ISSUE TITLE
Resource feedback tweak / bug.

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/app#300]
Hi @shouston3 @Danwhy @iteles 

When a user submits feedback on a piece of content, the text that they have entered remains in the text box which feels really confusing. It looks like it hasn't submitted - even though there is a message to say that it has.

Ideally the text and text box should disappear on submission?

**Comment by iteles** [comment]
@sarahwelton As there is a message telling the user submission has been successful, we thought they might want to see what they had commented on the resource.

We can go with whichever starting point for user testing you prefer 👍

**Comment by sarahwelton** [comment]
Ahh okay I see. So far the users I have tested with have found it confusing, but I'll continue to ask about it. Thanks.

**Comment by iteles** [comment]
That's great feedback! Happy to make this the starting point then and see where we go from here.

**Comment by iteles** [comment]
<img width="627" alt="screen shot 2017-06-21 at 15 38 43" src="https://user-images.githubusercontent.com/4185328/27389914-c1da12ca-5697-11e7-8917-98ad78e38f0f.png">
