### ISSUE TITLE
Image hosting

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#31]
Currently adding images in the wagtail rich text field only works in the cms locally.
This should be configured to also work in: heroku cms, heroku app and app locally.

This is currently not a requirement, but will certainly be needed in the future for when a cms user is writing an article.
Once implemented for images it will probably not be too difficult to configure for documents and other uploads

#### APP locally:
- [ ] Change embedded to actually be a image tag (4h)
- [ ] Ensure this does not affect the other configuration environments (1h)
#### Heroku CMS:
- [ ] Find something to react to for when an image get's uploaded (this will either be in the form of a polling script (not the best), script triggered by postgres, python code triggering script, python script. The script should upload the image to AWS (1d)
- [ ] Render this image to the CMS from AWS (4h)
#### Heroku APP:
- [ ] Change the form of the image "embedding" (this is the current form of the html string in postgres) when we serve up an image in an article (4h)

@Danwhy Let me know your thoughts on this these estimates or if there's more steps or if you've thought of another way around this problem
@nelsonic Is this a good way to be going about solving this problem (let me know if I need to clarify this problem more, it may be better to talk through it in person)
@iteles When and how do you think this issue should be tackled? (I'm having trouble thinking about the priority this one)

**Comment by Danwhy** [comment]
It looks like it might be possible to configure wagtail to upload images directly to S3: https://wagtail.io/blog/amazon-s3-for-media-files/
Hopefully this should make the 'Heroku CMS' stage a little simpler. Other than that, this looks about right to me

**Comment by shouston3** [comment]
@Danwhy You genius, that's at least knocked off 1d from the original time estimate (and sorted the uncertainty described in the "Heroku CMS" part)

**Comment by iteles** [comment]
@shouston3 I think you're right here that images is not required for sprint one given all we need right now is a landing page followed by a page with a list of links to relevant content. But it may be required soon, one to discuss with the rest of the team tomorrow.

**Comment by nelsonic** [comment]
@shouston3 S3 is the way to go. (_it's what we always use..._)
@Danwhy thanks for sharing the wagtail-specific link. 👍 
Let us know if you have any issues implementing it.

**Comment by shouston3** [comment]
Implemented in #351
