### ISSUE TITLE
Move 'Get urgent support' and 'Take Self Assessment' buttons to the sticky Alpha banner

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#322]
As a user, I want to be able to quickly and easily see that urgent support is available to me and also that there is the option of a self-assessment so that I trust the service and feel supported

Acceptance Criteria 
- [x] both buttons moved to the sticky Alpha banner
- [x] both buttons styled according to the style guide
- [x] both buttons linking to the same pages that they currently do

![alpha banner](https://user-images.githubusercontent.com/26304634/26934793-48e346fa-4c62-11e7-8696-3801686bceaf.png)

**Comment by Danwhy** [comment]
Do we have any designs for how this will look on mobile? Having the buttons in the banner + making them large enough to be clickable will take up a lot of mobile screen space, especially as the banner is fixed

**Comment by ellemindwave** [comment]
Thanks for highlighting this @Danwhy

@sarahwelton & @indiamindwave24 's domain - Please can you provide wireframes/UI and thoughts for how this could work?

**Comment by sarahwelton** [comment]
Hide on mobile for now. Users can access at the bottom of the page.

**Comment by sarahwelton** [comment]
<img width="354" alt="screen shot 2017-06-21 at 11 42 10" src="https://user-images.githubusercontent.com/26305143/27380356-b44d7f14-5676-11e7-9287-104213381b75.png">

**Comment by sarahwelton** [comment]
Please could the buttons hide as soon as they stack on top of one another?

**Comment by iteles** [comment]
@sarahwelton I've tested all the form factors available to us both on the development tool, including tablets and the larger phones (like iPhone x plus) but can't find one that displays them ontop of each other. Could you please clarify which device this happens on? 😊

**Comment by shouston3** [comment]
It happens on a Chrome browser at a width of 500px

![screen shot 2017-06-27 at 12 06 10](https://user-images.githubusercontent.com/15983736/27584753-1987ecca-5b31-11e7-8d90-c1de5fb27c77.png)

@sarahwelton good catch again 👍 

In future could you reference the device you were using when you find bugs and a screen shot if possible

**Comment by iteles** [comment]
@shouston3 As far as I'm aware, there is no device that is 500px wide.

**Comment by sarahwelton** [comment]
Sam is correct, I was looking on Chrome on my laptop. 

So I would see this if, for example, I was looking at two windows side by side. 

@shouston3 apologies - I will add device and browser in future :)
