### ISSUE TITLE
Editing 'share' icons on pieces of content

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#324]
As a user, I want to see universal share icons next to pieces of content so that I know I have options of where to share it privately

- [x] Share icons beside pieces of content to be Whatsapp, Messenger, email etc
- [x] Styling according to @indiamindwave24

**Comment by indiamindwave24** [comment]
[sharing_LDMW.zip](https://github.com/LDMW/app/files/1096215/sharing_LDMW.zip)

**Comment by iteles** [comment]
Note: I believe we should look to create a separate page or provide some feedback to the user when this is clicked. Something simple can be implemented on Wednesday afternoon after we have discussed and added as a separate issue.

**Comment by indiamindwave24** [comment]
Can we please add hover states [Sharing_hover.zip](https://github.com/LDMW/app/files/1104915/Sharing_hover.zip)

**Comment by sarahwelton** [comment]
<img width="1662" alt="screen shot 2017-06-27 at 11 42 02" src="https://user-images.githubusercontent.com/26305143/27583895-e537f10c-5b2d-11e7-9f4b-2bbca9fe21d1.png">
<img width="545" alt="screen shot 2017-06-27 at 11 42 13" src="https://user-images.githubusercontent.com/26305143/27583896-e542ff5c-5b2d-11e7-921c-60bbe1c73188.png">
<img width="401" alt="screen shot 2017-06-27 at 11 42 23" src="https://user-images.githubusercontent.com/26305143/27583897-e5478284-5b2d-11e7-9531-09372d7e1b07.png">

**Comment by sarahwelton** [comment]
The size of the icons is the same for desktop and mobile - but they shrink in between... why is this? If they are consistent for largest screen size and smallest screen size it would be logical that they are consistent across all in between screen sizes...

**Comment by ellemindwave** [comment]
@Danwhy the share icon alert no longer works - maybe due to the site reverting back to an older version?
