### ISSUE TITLE
Make 'search' or 'find' button much more obvious

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#326]
As a user, I want to immediately be alerted to the search/find button, so that I know what the purpose of my being on the site is, and I know straight away what I am meant to do. 

Acceptance Criteria:
- [ ] search button repositioning according to wireframes from @sarahwelton 
- [ ] search button restyling according to UI from @indiamindwave24

**Comment by ellemindwave** [comment]
![screen shot 2017-06-12 at 10 27 45](https://user-images.githubusercontent.com/26304634/27027759-82b8d9c6-4f5a-11e7-899f-402ed3b33956.png)

**Comment by sarahwelton** [comment]
<img width="587" alt="screen shot 2017-06-20 at 15 24 46" src="https://user-images.githubusercontent.com/26305143/27338277-a61b4944-55cc-11e7-8d73-023bfe0a77d8.png">
Slight amend (not even related to this issue!) but just thought I'd share to avoid confusion down the line. Have removed "scared" from the quick links.

**Comment by iteles** [comment]
@indiamindwave24 The integration of the search button within the input box is a departure from the current style of the website. Is it safe to assume that we want to stick the current styling and revisit this for beta?

Can you also please confirm that we now want _two_ search bars? (Duplicating this isn't something we had discussed so I wanted to confirm)

**Comment by indiamindwave24** [comment]
No it does not need to sit within. To the right hand side, please

**Comment by ellemindwave** [comment]
Hi @iteles - Yes, we would like to have 2 search bars. One to make the CTA more obvious as the first thing you see on the page, and another if you don't see the immediate category you need in the quick links
