### ISSUE TITLE
 How many users should we be testing the site for?

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#327]
@ellemindwave @sarahwelton what would be a rough number for this?

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/26933329-2a8fa5bc-4c5e-11e7-8a27-df225681cc8b.png)

**Comment by shouston3** [comment]
It seems heroku can facilitate far far more than we are currently getting.

@Danwhy tested `londonminds.co.uk` for 40 users arriving every second for 60 seconds and it coped, we should reopen this if we come close to this figure.
