### ISSUE TITLE
Adding video to homepage

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#331]
As a user, I want to land on the homepage and immediately be able to see a short video about the overall vision of the London Minds service, so that I understand that it is constantly growing and being updated, and to prompt me to keep checking in to see changes

London Minds video is being made by @indiamindwave24 Monday & Tuesday

Acceptance Criteria
- [x] London Minds video is embedded on homepage
- [x] Stacks on mobile
- [x] To be positioned to the right of the intro text

**Comment by shouston3** [comment]
@ellemindwave I'm adding the video to the right of the intro text.
On mobile the video will appear below the intro text

**Comment by shouston3** [comment]
Could you give this a once over test before we assign to MW people please

To test:

+ See there is a yt video on [app-staging](ldmw-app-staging.herokuapp.com)
+ Visit [`cms-staging > explorer > homepage](http://ldmw-cms-staging.herokuapp.com/admin/pages/3/edit/)
+ Edit the yt video url `&&` publish
+ See video has changed on [app-staging](ldmw-app-staging.herokuapp.com)
+ Vid should stack on mobile

**Comment by sarahwelton** [comment]
<img width="957" alt="screen shot 2017-06-21 at 11 27 51" src="https://user-images.githubusercontent.com/26305143/27379828-b3c931f2-5674-11e7-898d-581a281246ca.png">

The video should keep its ratio regardless of screen size.

**Comment by iteles** [comment]
@shouston3 This still isn't quite right.

On iPad mini, it looks like the right ratio:
<img width="452" alt="screen shot 2017-06-22 at 21 43 41" src="https://user-images.githubusercontent.com/4185328/27455722-33aca3c8-5796-11e7-9ac4-554528b11b91.png">

But on desktop, it's already squished:
![screen shot 2017-06-22 at 21 43 14](https://user-images.githubusercontent.com/4185328/27455740-44017384-5796-11e7-9ef1-220a86dee0b3.png)

These will all be youtube videos, can we try fixing the ratio of width and height using `rems` for example?

**Comment by sarahwelton** [comment]
![Uploading Screen Shot 2017-06-27 at 10.11.39.png…]()

**Comment by ellemindwave** [comment]
<img width="1020" alt="screen shot 2017-06-27 at 10 11 39" src="https://user-images.githubusercontent.com/26304634/27581000-4a22fa58-5b24-11e7-9541-fb94e10791a4.png">

**Comment by iteles** [comment]
@ellemindwave Agreed, this is why we hadn't assigned it to you yet 😊 

Although the above looks like it isn't actually a device/screen size, there are actually still some issues on ratios is some mobile device screen sizes 👍

**Comment by ellemindwave** [comment]
No problem!
You asked in Slack for us to go through and test the 'please test' issues - I didn't realise they had to be assigned to us as well as having the label, as they aren't always assigned to all of us anyway, apologies for jumping in! :) 👍

**Comment by iteles** [comment]
Not at all, I didn't explain that properly, thanks @ellemindwave!

**Comment by shouston3** [comment]
@iteles It's ready to test. I've opened it here for you to test: http://f5c516e5.ngrok.io/

I'll ensure that url is live for the next hour or so (or until you think it's ready to go)

**Comment by iteles** [comment]
Thanks @shouston3!
This is a pretty impressive number of media queries!

@sarahwelton @ellemindwave I think our breakpoint as it is now (tablets) for the video collapsing underneath the content may need to be moved to a little earlier so that the video doesn't get too small, but we can review tomorrow and change this in the afternoon as per your specifications.

**Comment by ellemindwave** [comment]
@shouston3 @Danwhy @iteles 
As per our conversation at the retrospective, am I to assume that the best thing here would be for this issue to be closed and a new one opened for the ratio/squashing issue?

**Comment by shouston3** [comment]
That would be great thanks @ellemindwave
