### ISSUE TITLE
Making it obvious which filters have been selected

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#333]
As a user, I want to easily be reminded what I have searched for and what filters have been applied to my list of results, so that I can amend it at any time to make it more relevant to me

Acceptance Criteria
- [x] According to wireframes from @sarahwelton 
- [x] According to UI from @indiamindwave24 
- [x] Filters that have been used in search are very visible, at the top/side of the list of results at all times

**Comment by ellemindwave** [comment]
![screen shot 2017-06-12 at 10 27 45](https://user-images.githubusercontent.com/26304634/27027556-d59e2372-4f59-11e7-9f4b-a57ee2b0cb6b.png)

**Comment by indiamindwave24** [comment]
Use the original styling for this, please. 
<img width="320" alt="screen shot 2017-06-21 at 13 36 09" src="https://user-images.githubusercontent.com/25007700/27384397-9a8f722a-5686-11e7-9799-4a6a3e19ff49.png">

**Comment by iteles** [comment]
@indiamindwave24 The new feature in this issue for us is the styling for the filters that are actually hidden away in the sidebar:
<img width="328" alt="screen shot 2017-06-21 at 18 12 18" src="https://user-images.githubusercontent.com/4185328/27397124-3cfdd3dc-56ad-11e7-8ae4-3528dd3b87b9.png">

Could you please clarify what those should look like? 
We know that the orange on white is rejected by the accessibility checks and the dark blue on white blends into the rest of the writing and users probably won't realise it's there.

**Comment by indiamindwave24** [comment]
This is the issue I was referring to earlier with the attached screenshot
<img width="888" alt="screen shot 2017-06-22 at 12 23 37" src="https://user-images.githubusercontent.com/25007700/27455941-00bca32c-5797-11e7-892c-b31b839710f7.png">

**Comment by sarahwelton** [comment]
![screen shot 2017-06-26 at 08 45 39](https://user-images.githubusercontent.com/26305143/27542961-b5f6e9d2-5a80-11e7-8cb7-c8dd3a2bc8e0.png)
<img width="432" alt="screen shot 2017-06-26 at 14 57 56" src="https://user-images.githubusercontent.com/26305143/27542962-b5fc2b68-5a80-11e7-8966-dc5560db23e9.png">

**Comment by sarahwelton** [comment]
<img width="432" alt="screen shot 2017-06-26 at 14 57 56" src="https://user-images.githubusercontent.com/26305143/27543066-fdf6380a-5a80-11e7-8d25-dfbfc380aa1f.png">
![Uploading Screen Shot 2017-06-26 at 14.59.47.png…]()

**Comment by sarahwelton** [comment]
Just to clarify - the "Filter" button has the exact same function as the previous "Filter" button. It is not a dropdown.

**Comment by iteles** [comment]
@sarahwelton Thanks for this clarification and for your time on the call just now.
We have agreed that from the current status in staging which looks like this:
<img width="582" alt="screen shot 2017-06-26 at 15 04 56" src="https://user-images.githubusercontent.com/4185328/27545148-08a268fe-5a87-11e7-82fb-7c82e71e9832.png">

We will change:
+ [ ] The tags showing immediately below the 'Showing x results for' line will include _only_ the tags that were on the homepage filters and not the ones in the sidebar
  + It was discussed that users might expect to see exactly what they searched for here (i.e. including the sidebar filters) but a preference was stated for testing the above proposed configuration first with users
+ [ ] Move the filter button (exactly as it was before) to below the line which says 'Showing x results'
  + This will be below the tags if there are any
