### ISSUE TITLE
Quick links for content above filtering section

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#334]
As a user, I want to be immediately provided with some options of things I may want to search for above the search box, so that I feel I am in the right place and I know I am not alone in feeling these things

Acceptance Criteria
- [ ] Wireframes from @sarahwelton 
- [ ] According to @indiamindwave24 
- [ ] Quick links act as an additional layer of tags in Wagtail
- [ ] In this sprint, they will not affect the logic of the layers below them
- [ ] Functionality for them to trigger conditional interactions when selected (for the layers of filters below) 

i.e. If 'Anxious' is selected as a quick link, then the questions that appear in the filtering system would be specific to someone suffering from anxiety, as opposed to sleep issues etc

**Comment by ellemindwave** [comment]
![desktop](https://user-images.githubusercontent.com/26304634/27131072-08266ee6-5101-11e7-8521-acb4291807e5.png)

**Comment by iteles** [comment]
Designs: https://github.com/LDMW/app/issues/366#issuecomment-310067948
