### ISSUE TITLE
immediate support link broken on homepage

### ISSUE THREAD

**Issue by katerobb** [LDMW/app#336]
@iteles we've just noticed that the immediate support link on the homepage is broken. Please can you look into it? Thanks
![screen shot 2017-06-09 at 10 53 13](https://user-images.githubusercontent.com/28757909/26970699-33911796-4d02-11e7-8599-f968dee67282.png)

**Comment by shouston3** [comment]
Nice spot, we're looking into this now

**Comment by shouston3** [comment]
@katerobb Should be fixed

**Comment by katerobb** [comment]
@shouston3 - i've just tested and all working fine. Thanks heaps for fixing!
