### ISSUE TITLE
"See more" changes ordering

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/app#348]
When I select "see more", the order of the resources is changing... or its deleting the first three options...

**Comment by shouston3** [comment]
Well spotted, we picked this up in #339 and have deployed the fix for https://ldmw-app-staging.herokuapp.com.

We will look to have this fixed in the next deployment to https://londonminds.co.uk

**Comment by iteles** [comment]
@shouston3 In that case, is this ready to move to `please-test` in staging?
