### ISSUE TITLE
Remove stubbing create wagtail database with travis

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#35]
Currently we are stubbing as of #29 

As discussed in #27 we could look at actually setting up the wagtail database and getting rid of stubbing. I think this could initially be a bit tricky but will pay off in the long run

**Comment by shouston3** [comment]
We will need to fill the database with some initial data for our tests to make sense, we should look in to the django way to do this. Models seem like the way to go: https://docs.djangoproject.com/en/1.11/howto/initial-data/

**Comment by shouston3** [comment]
As discussed with @nelsonic [here](https://github.com/LDMW/app/pull/29#pullrequestreview-34967800)

**Comment by nelsonic** [comment]
@shouston3 sounds like a plan. 👍

**Comment by shouston3** [comment]
Fixed with #37
