### ISSUE TITLE
Upgrade Heroku

### ISSUE THREAD

**Issue by Danwhy** [LDMW/app#352]
We need to upgrade heroku from the free tier. We should be fine to upgrade just to `hobby` for now, but we'll have to load test once we do.

@iteles Your card details are on the heroku account from when we added the custom url. Is it ok to go ahead with upgrading to `hobby`?

**Comment by iteles** [comment]
@Danwhy Yes please 👍 

Similarly to #353, we'll need to move this to NHS/MW soon.

**Comment by Danwhy** [comment]
Heroku upgraded to hobby and moved to MW details
