### ISSUE TITLE
Set up s3 ldmw account in dwyl's name

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#353]
We'll need your bank details to do so @iteles

**Comment by iteles** [comment]
@shouston3 Let's do one better: let's set this up whilst in the office tomorrow with the MW team and get the final card details as opposed to temporary dwyl ones :+1:

**Comment by shouston3** [comment]
Better idea 👍

We should also put the Heroku account in MW's name too while we're setting up the s3 account

**Comment by shouston3** [comment]
Duplicate of #378
