### ISSUE TITLE
Wireframes for desktop & tablet

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#354]
Desktop:
![desktop](https://user-images.githubusercontent.com/26304634/27078395-78f39bd4-502b-11e7-8c1d-7df0aaebf400.png)

Tablet:
![tablet](https://user-images.githubusercontent.com/26304634/27078426-94261af8-502b-11e7-8445-7da77f81b10f.png)

**Comment by iteles** [comment]
This is new!

@ellemindwave Have these been shown to any users yet?

**Comment by sarahwelton** [comment]
Just thinking ahead! We have a workshop this evening so will be running some thoughts past users - all the additions and amends you see here have come out of the user testing so far. 

These are initial wireframes. They still need some work before they go to India, but thought we should share our thinking with the wider team.

**Comment by ellemindwave** [comment]
![phone](https://user-images.githubusercontent.com/26304634/27127815-561eeaa4-50f4-11e7-9864-6b768041a6c3.png)

**Comment by iteles** [comment]
@shouston3 Can we please add a section to our documentation that refers to these latest wireframes?
It would be good to have it there for alpha release so that everything is kept together and we can update the documentation with further design references when we have them.
