### ISSUE TITLE
Ts&Cs page

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#364]
As a service user, I want to be able to see the terms and conditions of the site to check that it has a reputable team behind it so that I can trust the content I am seeing

Acceptance Criteria
- [ ] Ts & Cs page styled according to wireframes & UI from @sarahwelton and @indiamindwave24

**Comment by indiamindwave24** [comment]
Can this be set up as a page following link in footer and we can populate with content when we have it. This is something that is not dependant on us and so we do not yet have content to style etc.

**Comment by indiamindwave24** [comment]
@Danwhy there are no links in the footer to test

**Comment by Danwhy** [comment]
https://ldmw-app-staging.herokuapp.com/

**Comment by sarahwelton** [comment]
I've just added content into this page - it is very difficult to style content as desired (eg the spacing is weird, I can highlight and choose "P" for one piece of text and it appears completely differently to another "P" piece of text. As we can't "preview" pages either - we can only "publish" to view them -  we could end up in a very sticky situation once this service is out there. 

Also, H5s are displaying as 13pt font - for accessibility text must all be a minimum of 14pt. 


Shall we park this issue to discuss tomorrow @ellemindwave @indiamindwave24 @katerobb @iteles @Danwhy ?
