### ISSUE TITLE
Contact / About Us page

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#365]
As a user, I want to be able to quickly find out more about the London Minds team and contact them directly should I wish so that I trust the service more and can see who is behind it

Acceptance Criteria 
- [ ] About Us / Contact Us page styled according to wireframes and UI from @sarahwelton and @indiamindwave24

**Comment by Danwhy** [comment]
Empty page added to footer as per https://github.com/LDMW/app/issues/364#issuecomment-310507400
