### ISSUE TITLE
Ability to create static pages

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#367]
As a Service Provider, I want the ability to create new static pages in the CMS so that I can quickly adapt to the needs of the service and add pages without having to ask the development team

**Comment by shouston3** [comment]
@ellemindwave You can test this with the following:

+ From the admin view visit [explorer > homepage](http://ldmw-cms-staging.herokuapp.com/admin/pages/3/)
+ `add child page`
+ Choose `static page`
+ Publish the page
+ You should be able to link to this page with a `internal link` from any of the editable content panels

**Comment by sarahwelton** [comment]
The font styles don't match the live site. 


https://ldmw-app-staging.herokuapp.com/testing-new-feature

**Comment by shouston3** [comment]
@sarahwelton The font family should be 'NunitoSans' which is the same as what is on the homepage.
The `font-size` for paragraphs, list items and plain text on the `testing-new-feature` view is `20px` whereas the hompage it's `16px`.

If these elements are changed down to `16px` it will look like this:

<img width="653" alt="screen shot 2017-06-21 at 13 20 14" src="https://user-images.githubusercontent.com/15983736/27383926-e7cf79a6-5684-11e7-8218-c12a9ff76633.png">

Would that be what you want changed or do you want something else changed?

**Comment by iteles** [comment]
I don't see any documentation for this in the above PRs or in the CMS repo. We need to update this section before sending this for please-test: https://github.com/LDMW/cms#add-pages
