### ISSUE TITLE
Bugs to fix

### ISSUE THREAD

**Issue by Danwhy** [LDMW/app#368]
Bugs noted in the demo/sprint planning:
- [x] Email validation and whater you looking for validation gives 500 error
- [x] Alpha bar on mobile scrolling!
- [x] ‘2 filters selected’ should be bold
- [x] If you go back to ‘Show me everything’ it should appear as selected rather than ‘Select as many as are relevant’
- [x] Un-liking on mobile remains in active state (iphone only?)
- [x] London Minds logo too big on desktop (never go past half way point of text)
- [x] Alpha block alignment to the rest of the content
- [x] When you click ‘add your own’ filter, the feedback needs to be in the filter sidebar and styled as user feedback
- [ ] (Can't replicate - could have ben before we implemented keeping form data on error) Tabbing through the form - test and keep info when it you go away from it (chrome on mac)
- [ ] (Can't replicate) On mobile the page got stuck on a resource as they were scrolling and started working again on reload - Samsung android

**Comment by iteles** [comment]
@Danwhy Realised that 3rd from last checklist point was missing half a sentence, so update it 😊

**Comment by iteles** [comment]
@ellemindwave @sarahwelton 
The following 2 issues couldn't be replicated:
- Tabbing through the form - test and keep info when it you go away from it (chrome on mac)
  + We suspect this may have been that the user pressed submit by mistake and all of their data was lost as the testing was done before our latest change to ensure the data stays in the form
 - On mobile the page got stuck on a resource as they were scrolling and started working again on reload

We will deal with Un-liking on mobile remains in active state separately as this is an iphone only issue .

**Comment by shouston3** [comment]
@Danwhy @iteles can we close this?

**Comment by iteles** [comment]
@Danwhy A couple of issues in testing this:
+ [ ] Clicking on 'Add your own' appears to only show feedback on the _second_ time I click 'Add' - the first time I click and wait, it does nothing
+ [ ]  ‘Show me everything’ is selected when I select it from list specifically, but if I press search and come back to the sidebar, it goes back to 'Select as many as are relevant' - I assume this is because it's what can be done for now, but wanted to check with you first

**Comment by Danwhy** [comment]
Submitting 'add your own' is very slow due to it going to a google form. I'll have to add some 'submitting...' feedback to inform the users something is actually happening.
