### ISSUE TITLE
Add search feature

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#374]
As a user, I want to search the entire site for content that contains a certain word, so that I can quickly and easily find what I need

**Comment by sarahwelton** [comment]
Please could this be styled as per the style-guide? (ie use text input box style and the correct font)

**Comment by iteles** [comment]
@sarahwelton The font is Nunito Sans sized as in the style guide and the rest of the app, however, you're right, we're missing the 1px rounding on the input box - good spot!
