### ISSUE TITLE
UX for Sprint 5

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#381]
UX for Sarah / Kate:

- [x] Search CTA button / feature
- [x] Mobile wireframes for Assessment button & Urgent support in Alpha banner
- [ ] Feedback loop wireframes / logic
- [ ] Filter logic

**Comment by sarahwelton** [comment]
Not doing feedback loop now we've added search instead. 

![london_minds_20170620](https://user-images.githubusercontent.com/26305143/27380071-b475b304-5675-11e7-9f83-7106cc03dfa9.png)

**Comment by sarahwelton** [comment]
"Quick link" tags need to be editable / based on how we tag content (ie as it works now, but one level "above" the current system)
