### ISSUE TITLE
Hero image guidelines

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#386]
As an admin uploading a new hero image for the homepage, I would like to know guidelines for image dimensions and colour contrast

**Comment by shouston3** [comment]
Desirable image formatting would be:
+ the image contrasts well with white text on top of it
+ the image should be a wide, with a dimention ratio of approximately 3x2 (this can be found by highlighting the image then pressing `Cmd+I` on macs)

I need to find a good place to add this, perhaps the README

**Comment by sarahwelton** [comment]
Hi guys, 

Just came across this issue and thought I'd add some info... 

We know that it needs to contrast with the white text, so no need to document this. 

The information we were hoping you could provide is:

- max file size
- preferred file type (if there is one... PNG? JPG?)
- exact dimensions and if this needs to change across devices - obviously we want it to work on large screens, so providing you with a 300px x 200px image would not be suitable... 

Do we need to provide you with mock ups across devices so you can see how it should scale? Or is providing different images per device more appropriate?

**Comment by indiamindwave24** [comment]
Think that covers it, thanks @sarahwelton 👍

**Comment by shouston3** [comment]
#### Max file size

Wagtail allows for a maximum file size of 10MB (the current image is 500KB).

#### Preferred file type

Wagtail facilitates `GIF, JPEG, PNG`, but doesn't specify a preferred file type (you should go for `png` if you have the choice though)

#### Exact dimensions

I've tested it with a 300px x 200px (ish) image and it looks ok. The higher the resolution the clearer the image will be.

For the moment the try to use an image that will work across different sizes (the current image plays quite well with this).

Serving up different images depending on screen size would probably need its own separate issue

**Comment by iteles** [comment]
@shouston3 Can we add the comments you have above to our readme please?

**Comment by iteles** [comment]
@shouston3  I requested some additional changes in the PR please 😊

**Comment by shouston3** [comment]
@iteles let me know if others pop up 👍

**Comment by indiamindwave24** [comment]
Original: 
![yulia-chinato-33866](https://user-images.githubusercontent.com/25007700/27579473-8be8eace-5b1f-11e7-87e9-47db91ba490f.jpg)

Resized:
![yulia-chinato-338661](https://user-images.githubusercontent.com/25007700/27579568-e6ae39d2-5b1f-11e7-9bb5-07f3eeb0993f.png)

Resized to around 1MB:
![yulia-chinato-33866_1mb](https://user-images.githubusercontent.com/25007700/27579615-0da436f4-5b20-11e7-876a-1aab85786b28.png)

**Comment by iteles** [comment]
@indiamindwave24 You won't be able to read any of the text ontop of this image I'm afraid!
Also, so you're aware, when you upload an image to github as part of a comment it becomes compressed, so Google Drive is the best way to share these.
