### ISSUE TITLE
Make site password protected

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#39]
As a service provider I want to test the technical elements/functionality of the site with a closed group of users before opening it out to public testing so that I can make sure the main focus of the wider testing is on content & tone of voice etc, not functionality. 

+ [x] Site needs to be unsearchable 
 + [x] Site needs to only be accessible by password

* This password protect element can be removed from 9th June, and won't be needed thereafter*

**Comment by iteles** [comment]
Discussed with @sarahwelton and @indiamindwave24 on 27-April-2017, agreeing that for now, a single password that could be given to all users would be enough (decision to be revisited) and no data analytics impacts would be included in the early sprints.

Updated comment above @ellemindwave - please check ! I essentially removed:
>  + [ ] Each user should be able to have an individual ID/password so that we can track their journey
> @sarahwelton Please could you expand on the analytics side of things and what would be needed?

Also, could you please confirm what you mean by 'unsearchable'?

**Comment by shouston3** [comment]
Adding a [robots.txt](http://www.robotstxt.org/robotstxt.html) file with the correct information will tell google and other web crawlers to not be indexing our site

**Comment by ellemindwave** [comment]
@iteles What I meant by 'unsearchable' was that it no-one should be able to find it unless have the exact URL, and if they do come across it, it would be password protected anyway. Does that answer the question?

**Comment by ellemindwave** [comment]
@shouston3 @iteles There was discussion on Friday in Brighton that we are actually in fact allowed to go ahead with user testing as long as we make sure that there is no mention of links to the NHS. 
We were still discussing this on Tuesday in the content strategy workshop, and it has been decided that the password protect feature is now no longer needed for the site. 

Great news in terms of getting more users into the site to get testing things, but slightly annoying given the work that the team has done on setting up the password protect page. I can only apologise on their behalf for the mixed messages relating to election purdah - we were thinking the lock-down would be much stricter than it indeed seems to be.

**Comment by iteles** [comment]
@Danwhy Could you please add another issue to _remove_ the password protection from the website and we can make it a priority for the next sprint?

**Comment by iteles** [comment]
@ellemindwave This is having a bit of a knock-on effect for us which we are sorting out at the moment. Are you happy to close this?
As you said, a shame because it's all built already!

**Comment by ellemindwave** [comment]
Yes, happy to close this, and again very sorry about this situation! Frustrating and I know you guys worked hard to get this into place quickly. Thank you for being understanding. You never know, it might be needed again at some point....!
