### ISSUE TITLE
Filtering Logic

### ISSUE THREAD

**Issue by Danwhy** [LDMW/app#410]
When only one category has a filter applied to it, we still see all resources.

This is because the categories are set up to work with 'OR' logic, that is, show us any resources that have tags that are selected from category one OR category two.

The problem with this is that the filters are set to 'Show me everything' by default, meaning the logic that's getting applied is showing the selected tags from one category OR 'show me everything' from another category, which applies to all resources, meaning they all show.

We need to fix this by applying the logic to only 'Show me everything' from one category if it has one of the selected tags from the other category.

**Comment by iteles** [comment]
:+1: Now as expected!
