### ISSUE TITLE
Results vs Resources

### ISSUE THREAD

**Issue by Danwhy** [LDMW/app#414]
As a user, when I come onto the site having not performed a search, I expect to see 'Showing x resources' rather than 'Showing x results', as it is confusing to see 'results' for a search I have not done.

* [x] Change 'results' to 'resources' if a search has not been performed

**Comment by iteles** [comment]
I don't remember discussing this terminology with the MV team and thought the term was TBC. Was this a separate conversation @Danwhy?

**Comment by ellemindwave** [comment]
yes, this is what we discussed @iteles   'Showing x resources'.
However, @Danwhy please can we make this:

'Showing x resources about wellbeing' if a search has not been performed
