### ISSUE TITLE
Implement custom fonts

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#42]
Implement the custom fonts based on the designs/ style guide: 
<img src="https://cloud.githubusercontent.com/assets/16775804/25523681/8262a5d4-2bff-11e7-8023-cd9ba51e6d99.png" />
<img src="https://cloud.githubusercontent.com/assets/16775804/25523711/a48659d0-2bff-11e7-8391-93f402894bdb.png" />

**Comment by indiamindwave24** [comment]
[Segoe.zip](https://github.com/LDMW/app/files/969980/Segoe.zip)
[Nunito_Sans.zip](https://github.com/LDMW/app/files/969982/Nunito_Sans.zip)

**Comment by shouston3** [comment]
Looks good I'll have a go at adding these in

**Comment by Cleop** [comment]
Fixed in #55: https://github.com/LDMW/app/pull/55/commits/c432eb871624f46296516b9730a319f25656dda0

**Comment by indiamindwave24** [comment]
@Cleop @shouston3 The fonts don't seem to match with the designs. When I 'inspect', it says that they are correct but they do not appear the same. Is the character spacing different, perhaps?

**Comment by indiamindwave24** [comment]
The font 'arial' also appears in inspect? Is this what is showing?

<img width="748" alt="screen shot 2017-05-04 at 7 06 14 pm" src="https://cloud.githubusercontent.com/assets/25007700/25718098/c51a1fae-30fc-11e7-97e2-d34fa4f4e3f2.png">

**Comment by indiamindwave24** [comment]
I'm swooping in here - not sure where to pop this..

The text in the dropdown is far too small for accessibility, is should be as on style guide for GDS accessibility.
<img width="397" alt="screen shot 2017-05-15 at 10 08 44 am" src="https://cloud.githubusercontent.com/assets/25007700/26050466/a3cd68d0-3956-11e7-8ef2-6ac369be0a73.png">

**Comment by shouston3** [comment]
@Danwhy can this be closed?

**Comment by iteles** [comment]
@shouston3 Needs to be 'tested' by @ellemindwave first 👍

**Comment by ellemindwave** [comment]
Just spoken to @indiamindwave24 - fonts still aren't consistent, but for the purpose of closing this issue so that the sprint can be completed, I will close this issue, and India will raise a new fonts issue again when appropriate
