### ISSUE TITLE
End of alpha demo flow

### ISSUE THREAD

**Issue by iteles** [LDMW/app#430]
+ General overview of the website - "Showing 22 resources about wellbeing"
+ Alpha banner
  + Take self assessment **click event**
+ Header
  + Number of small niggles like the size of the logo
  + Hero image now editable #386 
  + Adding video
  + New search
    + Search for 'nightmare'
    + Search for 'peopl' to show partial word search
+ New filters
  + Filter on 'anxious' :arrow_right: show number of results
  + Filter on 'insomnia' from sidebar
+ Tags now clickable
  + Click 'community' and show sidebar
+ Show more button

This afternoon:
+ Share button 'reaction'
+ Static pages
+ IE testing

**Comment by reddog** [comment]
@iteles Just doing some issues pruning - can this be closed now?

**Comment by iteles** [comment]
@reddog Good spot!
