### ISSUE TITLE
Site crashing with wrong links

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#435]
When a link doesn't work it can bring down the homepage view

This can be replicated by adding in a link which doesn't exist in **any** of the resources

We should ensure that requests for links which don't exist fail gracefully

**Comment by shouston3** [comment]
The site can go down when someone links to a resource and then that resource gets deleted.

**Comment by reddog** [comment]
@shouston3 Appreciate you've done the work for this, but given #482 should it still be deployed?

**Comment by shouston3** [comment]
Should be fixed with #482
