### ISSUE TITLE
Script for checking links exist

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#436]
We should write a script which can get the raw html from the homepage, then send subsequent requests to all links on the homepage, then all links inside those and ensure that they all return non 40* or 50* status codes.

When we find these wrong status codes we should ensure that these links will be found correctly and that links can't be broken from the wagtail side.

At the moment we manually test routes and links can sometimes break.

**Comment by reddog** [comment]
@shouston3 Will this still be an issue post #482 ?

**Comment by shouston3** [comment]
No longer required due to #482
