### ISSUE TITLE
Alpha banner to beta banner

### ISSUE THREAD

**Issue by katbow** [LDMW/app#444]
For #433 

- [x] Change text for alpha banner to beta banner
- [x] Change button styling for self assessment & get support
    - [x] Remove background colour
    - [x] Update border radius
- [x] On scroll banner will be white.
    * with JS, without JS the banner is always white.

![image](https://user-images.githubusercontent.com/1287388/27790050-c2891a10-5fe6-11e7-9c65-138c40b31b09.png)

**Comment by Cleop** [comment]
Working on the scrolling part: https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onscroll

**Comment by sarahwelton** [comment]
<img width="1564" alt="screen shot 2017-07-07 at 13 24 58" src="https://user-images.githubusercontent.com/26305143/27957766-cd42f780-6317-11e7-826b-50cb69094763.png">

If you scroll down and then scroll back up, this happens.
