### ISSUE TITLE
Change primary button design

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#448]
- [x]  Change to dark blue background and white text
- [x]  Make corners less round
**Old design:**
![image](https://user-images.githubusercontent.com/16775804/27789326-0a8f4742-5fe4-11e7-9444-c95aa940c4db.png)
**New design:**
<img src="https://user-images.githubusercontent.com/16775804/27789334-199f7fea-5fe4-11e7-81dc-a7a0395defdc.png" width=120px />

**Comment by katbow** [comment]
This was done in conjunction with #451 in PR #456
