### ISSUE TITLE
Update the thumbs up/down symbols for bolder versions

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#450]
- [ ] Update the thumbs up/down symbols (for recommending a resource) for bolder versions to improve accessibility in blue
- [ ] Update the thumbs up/down symbols (for recommending a resource) for bolder versions to improve accessibility in orange
- [x] Make the 'Would you recommend this?' text bold
- [ ] Rearrange the thumbs up and number order:

**Currently (number - icon - icon - number):**
<img src="https://user-images.githubusercontent.com/16775804/27955549-41951092-630d-11e7-89cc-60f9e4b565d8.png" width=170px />
**Designs (icon - number - icon - number):**
<img src="https://user-images.githubusercontent.com/16775804/27955579-60d0566a-630d-11e7-878b-233511c715f0.png" width=170px />

**Comment by Cleop** [comment]
@indiamindwave24 - do you have the asset for this? 👍

**Comment by reddog** [comment]
No longer an issue (confirmed with @sarahwelton & @indiamindwave24 ).
