### ISSUE TITLE
Search Section

### ISSUE THREAD

**Issue by katbow** [LDMW/app#451]
For #433

- [ ] Change filters styling. Round edges, & remove background
    - [x] Round edges
    - [x] Remove background
    - [x] Change text & border colour
    - [ ] Change from white to blue plus
- [x] Add blurred image background instead of dark blue
- [x] Centre search bar & make full width
- [x] Centre filters on mobile, align left on desktop
- [x] Make search bar transparent (unless text cannot be black this way, then keep white #455 
- [x] On focus, search bar outline is orange
- [x] Change search button to new primary button design #448 
- [x] Move search button to half way point of the bottom of the section, below & in line with right of search bar.

![image](https://user-images.githubusercontent.com/1287388/27789987-7ce5a46a-5fe6-11e7-9fc3-a2c4749a7ac6.png)

**Comment by katbow** [comment]
external dependency is for blurred image.

**Comment by shouston3** [comment]
@katbow I think the blurred image might be [here](https://github.com/LDMW/app/issues/433#issuecomment-312618346)

**Comment by ellemindwave** [comment]
Here you go!

![filter_panel](https://user-images.githubusercontent.com/26304634/27791183-bc11a18e-5feb-11e7-81ee-9b50f954d2a2.png)

**Comment by katbow** [comment]
I realised the other asset I'm missing for this is the dark blue plus @ellemindwave

**Comment by katbow** [comment]
@ellemindwave @sarahwelton the only thing not done for this section is the white to blue plus. I have added it to a separate issue however, so this can be closed in lieu of that one if you are happy with everything else 👍
