### ISSUE TITLE
Create a new hideable section for Pros/Cons

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#452]
**Mobile view:**
<img src="https://user-images.githubusercontent.com/16775804/27789601-14608244-5fe5-11e7-8884-58e9fe113c72.png" width=350px />
**Desktop view:**
<img src="https://user-images.githubusercontent.com/16775804/27789818-ce38cfa0-5fe5-11e7-82d6-dc83fe40c582.png" width=400px />

- [x] Create a new section on Wagtail for pros and a separate new section for cons
- [x] Create a button on each resource to hide 'pros and cons' on mobile view
- [x] Do not display button on mobile if there are no pros or cons for that resource
- [x] Hide 'pros and cons' content on mobile view unless toggled by button
- [x] Display 'pros and cons' on desktop
- [x] Display pros in one section and cons in another (side by side on desktop)
- [x] Divide pros and cons with a line on desktop
- [x]  Display pros in one section stacked above cons in another (on mobile)

@sarahwelton - to implement this design we will have to create new pros/ cons sections on wagtail which means that the content which is in the body of the CMS will have to be copied and pasted into these new fields in order for this to work. Please let us know if you're not happy with this as someone from the MV team will have to copy and paste the existing content into the new sections.

**Comment by katbow** [comment]
Note for the button:
Because it has background blue on hover, in mobile this translates to the button changing & staying blue when clicked. For other buttons, this isn't a problem because it means going to a new link so the page renders again in some way & goes back to the main background colour. 

I'm checking for a way around this or looking for alternatives.

**Comment by katbow** [comment]
Changed the css for hover to only apply to `ns` screen sizes.

**Comment by Cleop** [comment]
@ellemindwave @sarahwelton - how would you like us to deploy this issue? In order to style the pros and cons to @indiamindwave24's new designs we have had to create 2 new sections on wagtail.

So currently all of the text is in the 'body' section, once deployed the regular text should go in the body section and the pros into the 'pros' section and the cons into the 'cons' section.  However, in order to update the CMS for this change the text will need to be manually copy and pasted from the body into these sections by the MV team. Are you able to do this on Monday morning in order for these sections to have content?

**Comment by ellemindwave** [comment]
@Cleop - I have discussed this with @sarahwelton and this is fine for us. 

We currently have an intern, Rania,  who is working with us helping with tags, content etc, so she will be able to help us out with this on Monday morning as this is one of her working days 👍

**Comment by sarahwelton** [comment]
<img width="438" alt="screen shot 2017-07-11 at 14 47 20" src="https://user-images.githubusercontent.com/26305143/28071503-0968a100-6648-11e7-98a8-814749dc4b74.png">

Alignment is off here (have posted in the "epic" as well)
