### ISSUE TITLE
Individual resource styling

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#453]
<img src="https://user-images.githubusercontent.com/16775804/27790261-a3a94a2e-5fe7-11e7-8eeb-dccef347c819.png" width=300px />

- [x] Create a dark blue border around the title / link/ tags/ copy section
- [x] Update link styling to underlined & colour
- [x] Update tags to new clickable styling
    - [x] Change background colour to light orange. ND: Shape should be the same as current, assuming rounded edges are mistake for mobile. They are shown as the same shape in desktop designs.

**Comment by katbow** [comment]
@Cleop what do you mean by:

> Ensure the existing shadow border is not visible where the new dark blue border is

It looks to me like the shadow is still by the border in the designs, but just doesn't look at obvious since the line from the border is cutting it off.

**Comment by Cleop** [comment]
@katbow, no problem, from a glance thought it wasn't there before but happy to go with it on closer inspection.
