### ISSUE TITLE
Video positioning for resources

### ISSUE THREAD

**Issue by katbow** [LDMW/app#466]
In #453, there is a new dark blue border which in the designs surrounds the title, links, tags, and body sections. 

There wasn't an example in the designs of where the video should sit if it available in relation to the border.

@ellemindwave @sarahwelton should this be inside the new dark blue border or underneath it?

Here's how it looks underneath the border:

![image](https://user-images.githubusercontent.com/1287388/27955308-234dddd6-630c-11e7-81f6-98b1a338f163.png)

**Comment by ellemindwave** [comment]
@katbow Please can the video be within the blue border? Thanks
