### ISSUE TITLE
Copy doesn't fit into mobile search box

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#473]
The new copy from the designs doesn't fit into the search box on mobile:
<img src="https://user-images.githubusercontent.com/16775804/27957588-fd6c7e14-6316-11e7-94db-84c1b6aeba0a.png" width=200px />
To fit it must be 12px on iPhone 5, which would not pass our accessibility requirements:
<img src="https://user-images.githubusercontent.com/16775804/27957727-9ec9977e-6317-11e7-8db1-62772aa74b2b.png" width=200px />

**Comment by sarahwelton** [comment]
"enter search term" < makes more sense for screen readers out of context as well.

**Comment by katbow** [comment]
@sarahwelton can you confirm if you would like that changed for both search inputs? Or should the one at the top stay as "What do you need support with?"

**Comment by ellemindwave** [comment]
@sarahwelton is currently in a meeting, but I think she meant for both search inputs, to make it clear for those using screen readers.

**Comment by katbow** [comment]
Okay great. Thanks @ellemindwave
