### ISSUE TITLE
Demo feedback

### ISSUE THREAD

**Issue by katbow** [LDMW/app#474]
**Beta banner**
- [x] Apply shadow on bottom (same as shadow around bottom part of resources)

**Search section**
- [x] Change "I am..." text
- [x] Change placeholder text to "Enter search term" #473 
    * ~done for search section, verifying if both need changing~ done for both
- [x] Increase opacity for search box

**Pros/cons**
- [x] On mobile, align text on the left with the body/title etc

**In general**
- [x] Ensure the logo is not hidden under the banner on other pages

**Comment by katbow** [comment]
@ellemindwave @sarahwelton - you mentioned in the demo changing the "I am..." text in the search section. Can you let me know please what to change it to?

**Comment by ellemindwave** [comment]
@katbow Sarah is on the tube, just tried calling her!  I take it it's not possible to make this content manageable in the time we have today? 

I _think_ Sarah wanted it to be 'I am or I know someone who is...'
but will have to get her to confirm @sarahwelton 

If she doesn't respond in time this evening, then leaving it and making it a point in next sprint to make that editable in the CMS would probably be a good option! :)

**Comment by ellemindwave** [comment]
@katbow UPDATED info. 

Sarah would like: 

'I am, or someone I know, is feeling:'

**Comment by ellemindwave** [comment]
@katbow All of these ready to go, but the logo doesn't seem to be loading on mobile or desktop on Chrome....?

![screen shot 2017-07-10 at 10 26 59](https://user-images.githubusercontent.com/26304634/28011457-5a746bd6-655a-11e7-8637-e818ded4420a.png)

**Comment by shouston3** [comment]
@ellemindwave should be fixed now: https://ldmw-app-staging.herokuapp.com/

**Comment by ellemindwave** [comment]
Great, thanks @shouston3
