### ISSUE TITLE
Tests for high levels of data

### ISSUE THREAD

**Issue by Danwhy** [LDMW/app#478]
We should write some tests to ensure our queries can handle pulling large amounts of data from postgres without timing out/crashing.

**Comment by reddog** [comment]
@Danwhy Is this still required given #482 ?

**Comment by Danwhy** [comment]
Probably not, we'll review it on Monday/Tuesday to make sure though.

**Comment by reddog** [comment]
@Danwhy Are we able to close this now?  If high load is a concern with the Wagtail instance then maybe we could open that separately to be addressed at some point?

**Comment by Danwhy** [comment]
👍 Looks to be good for now, will open a new one if ever necessary
