### ISSUE TITLE
Move required UI / functionality from Phoenix to Wagtail (retire Phoenix layer)

### ISSUE THREAD

**Issue by reddog** [LDMW/app#482]
As discussed yesterday at a group meeting, the project is (and continues to look for the foreseeable future) _like_ a CMS.  The Phoenix layer was predominantly introduced to facilitate direct peer-to-peer communication (over and above a regular forum, for instance) which is not a project requirement.  Increased use of _regular_ Wagtail functionality is a long term requirement.

The decision was taken to remove the Phoenix layer and move relevant UI and functional elements to the Wagtail codebase.

Once all UI/functionality has been migrated, the Phoenix layer will then be retired.

## Need to identify

- [ ] What the **user view** from the Wagtail instance _as-is_ looks like vs. current site (via Phoenix layer), ie delta between Wagtail instance and via Phoenix user views?
- [ ] What front-end UI code can be **copied** over as-is (part of the delta from above)?
- [ ] What front-end UI code needs to be **re-written** (remained of the delta from above)?
- [ ] What is the **functionality** from the Wagtail instance *as-is* vs. current site, ie delta in terms of functionality
- [ ] Is there any functionality that is not required (ie no longer required and hence shouldn't be copied over)?
- [ ] What is the functionality that will need to be **re-written**?

**Comment by shouston3** [comment]
1. User view from wagtail instance has absolutely nothing on it at the moment, see here: https://ldmw-cms-staging.herokuapp.com/
2. The front-end UI code should almost entirely be able to be copied over
3. Very little front-end UI code needs to be rewritten (if any)
4. Only the admin view will stay as it was before, the client view has nothing at the moment, but will have a lot more
5. We're assuming that all previous functionality is required and will aim to have it all as before
6. We've identified the functionality which will need to be re-written in this high level epic here: https://github.com/LDMW/app/issues/483

**Comment by reddog** [comment]
Closing in favour of https://github.com/LDMW/cms/issues/50
