### ISSUE TITLE
Rearchitechuring some of the ways we are storing our data

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#486]
From #483

### Resources

We currently have the resource page as the same type as the home page which leaves it with some unused fields.

We are planning to make Resources it's own page type (not a child of the home page) and ensure each resource is a child of the resources page

### Other static pages

The static pages are currently each their own page type, we should decide if we should keep these pages as a child of the home page or to have them on the top level

**Comment by Danwhy** [comment]
### Resources
Resources as their own page type, which we currently have, is a suitable way to display the resources, we just need to make sure their containing page is structured appropriately, ie: make a resources_index template which is rendered on the homepage, and itself renders all of the individual resources.

Resources should have their tags as they already do, but the top level tags we recently created would likely be better as 'categories'. Categories are a top level way to group content into pre-defined categories (These can be added via the wagtail admin panel), which are selected when a resource is created.

**Comment by reddog** [comment]
Is there a point where it would be useful for a quick (hand-drawn?!) picture of the current structure vs the new structure?

**Comment by reddog** [comment]
@Danwhy @shouston3 I know we've had a few conversations around how the resources sit within the home page, etc.

Although things might change in the future, are we done with this for the time being, or is there more to come?

**Comment by Danwhy** [comment]
I think we're done with this now, we've figured out enough about wagtails internal structure that we can be flexible about the structure/change it quite easily if we need to. @shouston3 agree?

**Comment by shouston3** [comment]
I feel this is done, closing 👍
