### ISSUE TITLE
Where should we put the wagtail instance?

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#488]
We could create the wagtail instance in this repo (where all of our previous commits, issues, wireframes are)

We could work off the wagtail instance here: https://github.com/ldmw/cms (where the current cms implementation is)

@nelsonic would be a good place to build this?

**Comment by nelsonic** [comment]
@shouston3 re-using the `cms` repo is a _good_ idea as it minimises disruption to the MWV team.

**Comment by shouston3** [comment]
👍 We'll port over our recently opened issues to: https://github.com/LDMW/cms/issues

**Comment by shouston3** [comment]
After a chat with @Danwhy we feel that it doesn't make very much sense to use what we currently have in the cms as the structure will almost entirely change (it was never built to be pulled out easily).

**Comment by shouston3** [comment]
See reasons [here](https://github.com/LDMW/app/issues/487#issuecomment-315754950)

**Comment by shouston3** [comment]
Moving over to cms repo
