### ISSUE TITLE
Page titles and descriptions for Google search

### ISSUE THREAD

**Issue by katerobb** [LDMW/app#496]
@ellemindwave @Danwhy 
The page titles and descriptions that I put into Wagtail don't seem to be pulling through / showing up on a Google search. The screen grab attached shows what looks to be the first paragraph on the page rather than the page description... Please can you look into this for me as we need Google to pick up the wagtail page titles and descriptions for SEO. Thanks!

![google search results](https://user-images.githubusercontent.com/28757909/31436055-93b961d6-ae79-11e7-95eb-145fcf2127be.png)
![sadness page title and description in wagtail](https://user-images.githubusercontent.com/28757909/31436133-d67246dc-ae79-11e7-82a8-c00958f515e1.png)
![sadness page copy on wagtail](https://user-images.githubusercontent.com/28757909/31436134-d7fc502e-ae79-11e7-9119-df03a3eecf9c.png)

**Comment by ellemindwave** [comment]
This issue has been moved over to the cms repo - should be closed in here but I don't have the option to
