### ISSUE TITLE
Landing page: cover image

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#50]
- Need cover image, please can you provide us with this @indiamindwave24

**Comment by indiamindwave24** [comment]
This is something that will definitely be changing as the project progresses. 
![london_minds_placeholder](https://cloud.githubusercontent.com/assets/25007700/25614336/7909dd86-2f29-11e7-9387-c86c1eedf7d4.png)

**Comment by shouston3** [comment]
Looks great @indiamindwave24 👍

**Comment by Cleop** [comment]
thanks @indiamindwave24, slight issue... you now can't read the text as this image is lighter than the previous one. I'm going to try and add a slight opacity/filter thing over it and see if it's improved but otherwise (depending on how you stretch the background image) you get:

![image](https://cloud.githubusercontent.com/assets/16775804/25616485/f54fb450-2f34-11e7-87df-1aad91862b5b.png)

OR

![image](https://cloud.githubusercontent.com/assets/16775804/25616546/5af635fe-2f35-11e7-9c59-df8e2f776865.png)

OR

![image](https://cloud.githubusercontent.com/assets/16775804/25616559/69dc2484-2f35-11e7-8974-4dc7643f5887.png)

**Comment by Cleop** [comment]
There are 2 ways to use opacity. The first one doesn't solve the problem:
![image](https://cloud.githubusercontent.com/assets/16775804/25616710/45add9e4-2f36-11e7-98e7-8b9217f20af8.png)
I think the second one will but having checked, I know that it's not accessible on IE8. In which case, on IE8 you would see a plain black background with white text but no background image.

Have you got an alternative design or would you like the alternative version which would be plain black with white text on IE8?

**Comment by indiamindwave24** [comment]
@Cleop For the time being, can we use this image:
![london_minds_placeholder_02](https://cloud.githubusercontent.com/assets/25007700/25625325/221822aa-2f54-11e7-8346-90b8f50294e0.png)
With an overlay of  #242E50 at 70% opacity
<img width="322" alt="screen shot 2017-05-02 at 4 22 14 pm" src="https://cloud.githubusercontent.com/assets/25007700/25625336/2cafdc58-2f54-11e7-9e0e-b1f2c1178706.png">

**Comment by Cleop** [comment]
Thanks @indiamindwave24, this new image seems somewhat better. The issue still remains that I can either only alter opacity **including the font** like this:

70% opacity and dark-blue overlay: 

![image](https://cloud.githubusercontent.com/assets/16775804/25626162/88b1c0d2-2f56-11e7-9c99-366b52d65788.png)

or without any overlay:
![image](https://cloud.githubusercontent.com/assets/16775804/25625835/817dde46-2f55-11e7-9de5-8c87e6176b7e.png)

I can implement the solution that will not affect font opacity and look perfect **except** that on IE8 users will only see because that technical implementation is not supported by IE8:

![image](https://cloud.githubusercontent.com/assets/16775804/25626245/ca40d92a-2f56-11e7-8b31-7d05a87d5316.png)

**Comment by indiamindwave24** [comment]
@Cleop Is there no way to have it like the screenshot above?

- Normal image 100% opacity
- Dark blue overlay 70% opacity
- White text 100% opacity

**Comment by indiamindwave24** [comment]
@Cleop This is the image WITH the overlay included. Does this overcome the issue?
![london_minds_placeholder_02_with_overlay](https://cloud.githubusercontent.com/assets/25007700/25627081/66f62f5c-2f59-11e7-938b-1b43fadeb663.png)

**Comment by Cleop** [comment]
That is definitely the best solution! Don't know why I didn't think of that before! @indiamindwave24

**Comment by Cleop** [comment]
Fixed by #54
