### ISSUE TITLE
Landing page UI

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#52]
- [x] Create top Alpha banner (hard coded)
- [x] Style Div for cover image/text
- [x] Add logo, #49 
- [x] Add background cover image, #50 
- [x] Create lower navy section
- [x] Add take part button
- [x]  Create white footer
- [x]  Add email input bar
- [x]  Style dropdown menu

All for mobile and desktop

**Comment by Cleop** [comment]
Fixed by #54

**Comment by indiamindwave24** [comment]
Alpha banner text is really small on mobile 
<img width="402" alt="screen shot 2017-05-17 at 8 27 39 am" src="https://cloud.githubusercontent.com/assets/25007700/26143041/19b50816-3adb-11e7-8f50-348e2256e10f.png">

**Comment by shouston3** [comment]
@indiamindwave24 I've put the remaining task into issue: #182 
As the rest seem done closing this issue. If there are any further issues to address here, please open another issue and we can add a time estimate to it
