### ISSUE TITLE
Landing page: alpha sign up email functionality

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#59]
At the moment there is an input field on the Alpha section of the landing page, however it is not functional.  

When a user enters their email address into the Alpha section they should be added to a mailing list.

As a service provider, I want to gather email addresses of users who are interested in being involved with the alpha phase into a Google spreadsheet so that I can get in touch with them to give them more information, help them get involved and ask for valuable feedback

- [x] Text field to enter email address
- [x] Descriptive text about Alpha & what it involves
- [x] 'Take part' button that is clickable once the text input field is populated
- [x] Success message when the email address is successfully entered ( issue #108 )

**Comment by shouston3** [comment]
Putting them into a google spreadsheet

**Comment by Cleop** [comment]
User story from @ellemindwave: 

As a service provider, I want to gather email addresses of users who are interested in being involved with the alpha phase into a Google spreadsheet so that I can get in touch with them to give them more information, help them get involved and ask for valuable feedback

**Comment by shouston3** [comment]
Alert if the email address is not valid.

How important is this?

The others are not too hard to achieve, but that would take quite a bit of work

**Comment by iteles** [comment]
@ellemindwave We are going to be dealing with the email address validation in a separate issue (#108), so this issue is now ready to be tested.

Note: We have an elementary success message in there for now, we will style this as per #108 and add validation as per that issue next 👍 

Please test on staging 😊

**Comment by indiamindwave24** [comment]
@shouston3 Styling of this section is not as on styleguide
<img width="403" alt="screen shot 2017-05-15 at 10 00 38 am" src="https://cloud.githubusercontent.com/assets/25007700/26050144/87a2fa90-3955-11e7-876f-10d0da2e95b2.png">
<img width="640" alt="screen shot 2017-05-15 at 10 00 30 am" src="https://cloud.githubusercontent.com/assets/25007700/26050143/87a22b60-3955-11e7-9978-df38fa726f85.png">

- [ ] Header styling (ALPHA, what does it mean?)
- [ ] Header styling (take part in our Alpha)
- [ ] bullet points
- [ ] Text box should be same width as text area
- [ ] 'Take part' button should be right aligned BELOW text box, centrally positioned on edge of white card
