### ISSUE TITLE
Landing page: add option to order resources by 'relevance'

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#63]
- Need to add 'Order content by most relevant'

**The designs:**

<img src="https://cloud.githubusercontent.com/assets/16775804/25664594/05d57d62-3013-11e7-9e32-a0ec9497dd10.png" width=300px />

Will resources automatically be ordered by most relevant and so is this needed? 

Or should this now say something different like 'Order content by newest'? Or would the design look cleaner without this functionality as there will be quite a lot going on there when you've also got the multiple tags after the drop down menu? so we don't want to overwhelm people.

@ellemindwave @indiamindwave24

**Comment by indiamindwave24** [comment]
Ignore this for the time being - tags only at the mo :)

**Comment by Cleop** [comment]
**Update on designs:**

**Desktop design:**
<img src="https://user-images.githubusercontent.com/16775804/27790495-8d6556c6-5fe8-11e7-9b56-ca47c876b6f6.png" width=240px />
**Mobile design:**
<img src="https://user-images.githubusercontent.com/16775804/27790508-a276a31c-5fe8-11e7-90b4-84f2417985a8.png" width=160px />

Still no update on functionality. @sarahwelton, @indiamindwave24 added this to the designs again but we discussed that we still have no functionality for this, so leaving this out of the designs for now. Please confirm that this is the right understanding?

**Comment by ellemindwave** [comment]
@Cleop Yes, that's the right understanding. Leave it for now 👍
