### ISSUE TITLE
Landing page: style the filtering options for resources

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#64]
**Need to implement designs for the filtering choices for resources:**

<img src="https://cloud.githubusercontent.com/assets/16775804/25666765/5be5f4d8-3019-11e7-9a75-c63a9b04f136.png" width=240px />

Awaiting designs from @indiamindwave24, when you're able 👍

**Comment by indiamindwave24** [comment]
<img width="396" alt="screen shot 2017-05-04 at 4 51 42 pm" src="https://cloud.githubusercontent.com/assets/25007700/25714714/cc5b69f0-30f0-11e7-8a91-61273c17d8a5.png">

**Comment by Cleop** [comment]
Closing, duplicate of #83
