### ISSUE TITLE
Changing weighting of content in searches (for forums)

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#69]
As a service provider, I want to be able to prioritise and weight content more heavily if it involves an element of peer to peer, so that users feel connected to other people like them

As a service user, I want to see the most relevant, trusted useful content first when I search, so that I can find the information I need quickly and effectively

- [ ] When searching, 'peer to peer' resources should appear higher in the listings that other content
- [ ] Peer to Peer resources are any resources that involve an interaction with other users - top priority for Sprint 2

**Comment by Danwhy** [comment]
On the CMS, Resources can now be give a priority on the 'Promote' Tab
