### ISSUE TITLE
'Would you recommend this to others' thumbs up/down functionality

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#70]
As a service provider, I want to enable users to quickly rate content based on whether or not they would recommend it to others, so that we start to generate feedback on what is useful for users and can prioritise this for the right people

As a service user, I want to quickly rate a piece of content based on whether or not I would recommend it to others, so that I am helping the service providers make sure the most useful content is being recognised

Acceptance criteria:
- [x] Thumbs up and thumbs down icons with hover state, selective state and counter
- [x]  Counter should display number of selects 
- [x] Counter should remember a repeat visitor
- [x] Styled to provided UI designs
- [x] Text should read 'Would you recommend this to others?'

**Comment by ellemindwave** [comment]
The position for where this should is on @sarahwelton 's wireframes http://f86j98.axshare.com
Just awaiting designs from @indiamindwave24 for the UI

**Comment by indiamindwave24** [comment]
<img width="193" alt="screen shot 2017-05-04 at 5 57 37 pm" src="https://cloud.githubusercontent.com/assets/25007700/25715363/2efaea34-30f3-11e7-84d0-9ae2acc00389.png">
[Thumbs_up_down.zip](https://github.com/LDMW/app/files/976971/Thumbs_up_down.zip)

**Comment by indiamindwave24** [comment]
[Thumbs_up_down.zip](https://github.com/LDMW/app/files/976980/Thumbs_up_down.zip)
<img width="193" alt="screen shot 2017-05-04 at 5 57 37 pm" src="https://cloud.githubusercontent.com/assets/25007700/25715838/d58504f6-30f4-11e7-960e-4720513e88e8.png">

**Comment by shouston3** [comment]
#### How to store likes and dislikes for each article (technical)
We are looking to store likes and dislikes for each article (along with a session id to store who liked it)
The articles/resources we referencing are from a readonly database and we need to make a reference to these when we store the likes and dislikes
@nelsonic suggested something like [this](https://github.com/nelsonic/time-mvp/blob/master/lib/database_setup.sql#L41), but we could also look to see what the `conn` map has to offer
When we render the homepage, we should get each article from the cms database, and get all of the likes for these.
When someone likes/dislikes something we should store this with a reference to the article id stored in the cms database
@Danwhy @nelsonic @SimonLab let me know your thoughts on this

**Comment by indiamindwave24** [comment]
This still does not function correctly. I cannot 'unlike'

I am using iPad Pro 12" safari

**Comment by iteles** [comment]
@indiamindwave24 I tested this on an iPhone 5, iPhone 6 and iPad mini before we assigned this to you, looks like it might be an isolated iPad Pro issue.

Could you please bring your iPad Pro into the office tomorrow (Tuesday - we'll be in for the user testing) so that we can debug with the device?

**Comment by iteles** [comment]
Closed and added comment to the issue for the bug itself: https://github.com/LDMW/app/issues/385
