### ISSUE TITLE
Add Tag Manager functionality to track share icon click event

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#71]
As a service provider, I want to track how many users click on the share icon, so that I can see whether the demand for a share button exists, or whether the share functionality on Android and iOS is sufficient

- [ ] Ability to track clicks to the 'share' icon, so that we can understand demand for sharing content

**Comment by Danwhy** [comment]
This is ready to go as soon as I'm added as a user to the Google Analytics account

**Comment by Danwhy** [comment]
Clicking the share button should now add a new event to the Google Analytics
