### ISSUE TITLE
Add 'What else is affecting you today?' input box also saving to Google spreadsheet (wording TBC)

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#73]
As a service provider, I want to capture what issues (other than sleep) users are facing so that I can understand what the main focus should be after the Alpha phase

Acceptance Criteria:
- [x] Free text box that populates into a Google spreadsheet
- [x] On submission, text should populate into a Google spreadsheet and user should get a message saying 'Thank you for your input, it will be used to improve and develop the service further. Let us know if you have any more feedback'
- [x] Styled according to UI 
- [x] Exact text TBC by Mindwave on Wednesday 10th May (after content workshop on Tues 9th)

**Comment by Cleop** [comment]
@sarahwelton @indiamindwave24  - would be great to know where this should be positioned on the page

**Comment by ellemindwave** [comment]
@Cleop Adding the link to the wireframes for this here:
http://f86j98.axshare.com 

As you'll see, it is positioned at the bottom of the page, underneath the content. Any questions - please shout!

**Comment by indiamindwave24** [comment]
<img width="187" alt="screen shot 2017-05-04 at 6 15 45 pm" src="https://cloud.githubusercontent.com/assets/25007700/25716071/b7cca4fe-30f5-11e7-840e-c6f39c6a52ac.png">

**Comment by shouston3** [comment]
Should be ready to go @ellemindwave 
Has the above wording been confirmed?
Is "Thank you for your input, it will be used to improve and develop the service further. Let us know if you have any more feedback" the wording you would like to go with?

**Comment by ellemindwave** [comment]
HI @shouston3 - for now, the text you have put in is fine 👍
