### ISSUE TITLE
Adding a generic share icon to content

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#74]
As a service provider, I want to have a generic share icon on the pieces of content so that users can easily share pieces of content they have found useful

Acceptance Criteria
- [x] Share icon to feature beside the 'Would you recommend this to others?' at the bottom of each piece of content

 In the first instance (Sprint 2) this button won't have any functionality, the purpose will be to track how often users click on the button to see whether or not sharing is something that is in demand

**Comment by Cleop** [comment]
- Awaiting design

**Comment by indiamindwave24** [comment]
[Share.zip](https://github.com/LDMW/app/files/977013/Share.zip)
