### ISSUE TITLE
Crisis page

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#75]
As a service provider, I want to make sure that should a user be in a crisis and need urgent help, I am directing them to somewhere where they can access 24/7 help so that their situation doesn’t become worse and so that I am fulfilling my duty of care to that user

As a service user, I want to know that should I need urgent help, I will be directed to the appropriate place to receive adequate support so that my situation doesn’t become worse

- [x] Crisis page containing numbers / contact details for urgent medical assistance (content will be similar in style to HealthLocker page)
- [x] Styled according to UI designs
- [x] Linked to by a banner on the landing page 'If you are in need of urgent help, please click here' COPY TBC - Content Strategy workshop on Tuesday 9th May
- [x] Banner on landing page styled according to UI

**Comment by Cleop** [comment]
- Awaiting design

**Comment by indiamindwave24** [comment]
![crisis](https://cloud.githubusercontent.com/assets/25007700/25749035/0a838320-31a5-11e7-9712-9147a8e9a408.png)

Content and Icon subject to change as taken from HL...

[Crisis.zip](https://github.com/LDMW/app/files/979303/Crisis.zip)

**Comment by indiamindwave24** [comment]
![crisis](https://cloud.githubusercontent.com/assets/25007700/25749341/0f127a76-31a6-11e7-9597-4172729da130.png)

**Comment by indiamindwave24** [comment]
<img width="361" alt="screen shot 2017-05-08 at 15 00 54" src="https://cloud.githubusercontent.com/assets/25007700/25808027/b5a19e6a-3400-11e7-949d-41aa9092ed03.png">
copy TBC
