### ISSUE TITLE
Hook up alpha banner email to mailto link

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#76]
As a service provider, I want to gather feedback from users on the alpha prototype and make sure that we are taking user feedback into consideration so that we can design a product that best suits the user needs

As a service user, I want to be able to quickly provide feedback on the alpha prototype so that I can influence the design and make the product as good as possible

**Comment by Cleop** [comment]
@ellemindwave please could you confirm that the email for this is sarah@londonminds.com?

**Comment by ellemindwave** [comment]
@Cleop Yes, it is sarah@londonminds.com 👍 

@sarahwelton

**Comment by sarahwelton** [comment]
@cleop - apologies, its sarah@londondminds.co.uk

**Comment by sarahwelton** [comment]
Oops my bad - this has been updated! Thanks guys.
