### ISSUE TITLE
'Take a sleep assessment' button with coming soon holding page 

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#77]
As a service user, I want to be able to see that there is the offer of a clinically moderated triage tool available to me, should I wish to take it, so that I can find out more about my circumstances and needs

Acceptance Criteria
- [x] Sleep assessment button and introductory copy on landing page
- [x] Must say that it is clinically approved
- [x] Styled according to UI
- [x] Holding page must be styled to UI design
- [x] Holding page only accessible by clicking on the 'Take sleep assessment' button

**Comment by Cleop** [comment]
Would be great to get a design from @indiamindwave24 or an indication from @sarahwelton where on the page this button should appear (if India is happy for this to be a primary button).

**Comment by ellemindwave** [comment]
The button should appear in the top right hand corner, as per the wireframes here http://f86j98.axshare.com
@indiamindwave24 @sarahwelton

**Comment by indiamindwave24** [comment]
![coming_soon](https://cloud.githubusercontent.com/assets/25007700/25748893/a9832832-31a4-11e7-9f15-af96fcc07086.png)
[Coming_Soon.zip](https://github.com/LDMW/app/files/979289/Coming_Soon.zip)

**Comment by indiamindwave24** [comment]
<img width="258" alt="screen shot 2017-05-08 at 13 36 48" src="https://cloud.githubusercontent.com/assets/25007700/25806887/c4952bf2-33fc-11e7-8f86-8e9e7cfcc298.png">

**Comment by ellemindwave** [comment]
@iteles I can't see this button when I look on the site currently?

**Comment by shouston3** [comment]
It should be on: https://ldmw-app-staging.herokuapp.com/ with username: ldmw, password: wNU8pSVB

**Comment by indiamindwave24** [comment]
This looks great :)

Although the coming soon page should not be sitting within a card
<img width="373" alt="screen shot 2017-05-15 at 9 55 19 am" src="https://cloud.githubusercontent.com/assets/25007700/26049923/af5e06ac-3954-11e7-8a14-4bea0893f5ec.png">
