### ISSUE TITLE
Landing page: style resource filters

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#83]
**As a** LM user...
**I want to** be able to easily filter the resources I am searching for...
**so that** I see the results that the most relevant to my needs.

- Awaiting design from @indiamindwave24 
- Initially going to style checkboxes to resemble the tags (currently displayed in resource results) with alternating colours for active/inactive.

**Comment by Cleop** [comment]
This is what has been done based on the other tag designs:

![image](https://cloud.githubusercontent.com/assets/16775804/25709690/e6cfef36-30e1-11e7-982a-4186176f765b.png)

Filled orange = selected, orange border but empty = not selected.

**Comment by indiamindwave24** [comment]
Yes, this is fine for tomorrow :) I have been working on filters this afternoon and done this - not a million miles away!

<img width="396" alt="screen shot 2017-05-04 at 4 51 42 pm" src="https://cloud.githubusercontent.com/assets/25007700/25712635/13874a30-30ea-11e7-9e21-ed4c5f630066.png">

**Comment by Cleop** [comment]
**As a** LM user
**I want to** see a pointer cursor when I'm hovering over a button
**so that** I am aware that I can click on it/ it is a button.

- Add pointer class so that on hover users can see

**Comment by Cleop** [comment]
Thanks @indiamindwave24, would you be able to pop the assets for the tick and cross on this issue? I've made the colour changes.

**Comment by indiamindwave24** [comment]
@Cleop [Success_Error.zip](https://github.com/LDMW/app/files/978901/Success_Error.zip)

**Comment by Cleop** [comment]
I think you may have sent across the wrong files @indiamindwave24 - the crosses are X's instead of +'s and the icons are in coloured circles... would you be able to give it another go?

**Comment by indiamindwave24** [comment]
OH sorry, I thought you wanted the tick and cross for the text fields, silly me!
[Tags.zip](https://github.com/LDMW/app/files/979357/Tags.zip)

**Comment by Cleop** [comment]
Still to do:
- Responsive spacing
- Create a turquoise highlight around each tag for keyboard navigation so that a user can tell that is the element they are currently controlling. Similarly to: 

<img src="https://cloud.githubusercontent.com/assets/16775804/25843382/1e8c2aaa-349f-11e7-87dc-6799d31e0966.png" width="100px" />
