### ISSUE TITLE
Landing page: dropdown menu styling and broswer compatibility

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#84]
The current design for the styling of the dropdown menu for resource categories:
<img src="https://cloud.githubusercontent.com/assets/16775804/25698987/2e006c4c-30b9-11e7-978e-966d3c04bfda.png" width=270px />

However this design will require javascript to be implemented and this does not comply with the [GDS requirements](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices). Is there an alternative option that can be explored?

**Comment by indiamindwave24** [comment]
GDS require you to have an alternative solution if Java is not available — Please use native dropdown where java is not available (as is on current site).

**Comment by iteles** [comment]
:+1: This has now been superseded by #133
