### ISSUE TITLE
Site entry page: style password entry page

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#85]
**As a** LM user
**I want to** get a positive first impression of LM
**so that** I trust and have confidence in using the resource.

Styling the password entry page will ensure users have a positive first impression and know they're in the right place.

Will just do basic styling based on the style guide so it doesn't look awful!

**Comment by iteles** [comment]
Basic styling so far:

![screen shot 2017-05-04 at 20 12 58](https://cloud.githubusercontent.com/assets/15983736/25720824/3434e8fc-3106-11e7-85a4-f07af403374b.png)

**Comment by indiamindwave24** [comment]
This is great!

Obviously not urgent as what we have here is great but a few changes when you get the chance:

- [ ] 'To access the site...' If the bounding box for text can be the same width as the white box, that would be great
- [ ] Text boxes should follow styling from the style guide
<img width="164" alt="screen shot 2017-05-05 at 12 06 39 pm" src="https://cloud.githubusercontent.com/assets/25007700/25743261/61a49550-318b-11e7-8f60-0b3885f24ce1.png">

- [ ] Button should be left aligned to text box
<img width="134" alt="screen shot 2017-05-05 at 12 07 39 pm" src="https://cloud.githubusercontent.com/assets/25007700/25743310/95cf7638-318b-11e7-9cf8-e2f81baaaa13.png">

**Comment by indiamindwave24** [comment]
[Success_Error.zip](https://github.com/LDMW/app/files/979362/Success_Error.zip)

**Comment by ellemindwave** [comment]
closing this as the password protect page is no longer needed - even though I haven't seen it in action... @Cleop
