### ISSUE TITLE
Default content to display

### ISSUE THREAD

**Issue by Danwhy** [LDMW/app#87]
@ellemindwave @sarahwelton 
What do we want to show when a user comes to the site, before they have selected a sleep issue or other tags? Do we want to show all of the resources available, or just a select few? If just a few, should we be using the weighting (https://github.com/LDMW/app/issues/69) to decide which ones?

**Comment by iteles** [comment]
Removing from sprint as not in agreed scope.

**Comment by ellemindwave** [comment]
Relates to #129 - Current plan is that there will be content blocks showing 3 pre-defined bits of content
