### ISSUE TITLE
Application + CMS Overview Diagram

### ISSUE THREAD

**Issue by nelsonic** [LDMW/app#9]
This is meant to be a _basic_ overview of what we are building:

![ldmw-application-architecture-diagram](https://cloud.githubusercontent.com/assets/194400/25229096/cd075eb6-25c6-11e7-8233-5712d55a20fe.png)

Click on image to see large version.
To edit: https://docs.google.com/drawings/d/1NX710eQ_1fJgxctvF3--KOO4S-m-_lOouWg1V_lPtXY

**Comment by shouston3** [comment]
Great, thanks for clarifying this, super cool idea btw. This has been merged into readme in #14, closing
