### ISSUE TITLE
Integrate Tenon with travis/precommit?

### ISSUE THREAD

**Issue by Danwhy** [LDMW/app#93]
We should investigate hooking up the Tenon api (https://tenon.io/) to Travis or a precommit hook to ensure we are consistently keeping to accessibility guidelines

**Comment by Danwhy** [comment]
Tenon seems like it would get quite expensive for our use case. [pa11y](http://pa11y.org/) looks like it could be a good alternative.
* [Github](https://github.com/pa11y/pa11y)
* [Pa11y CI](https://github.com/pa11y/ci)

**Comment by Danwhy** [comment]
Managed to set up a precommit hook, but had trouble getting it to work with Travis. Precommit should be good enough for now, but will have to revisit at a later date.

**Comment by SimonLab** [comment]
The precommit should now be on the master branch now that #117 is merged. Happy for you to close this issue @Danwhy (or keep it open if you want to try pa11y with CI)
