### ISSUE TITLE
Wireframes for Sprint 2 features

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/app#94]
- [x] 'Would you recommend this? 'Thumbs up - thumbs down
- [x] 'What else do you want help with?' input field
- [x] Sleep Assessment button
- [x] Password protection screen
- [x] Crisis banner underneath 'what else do you want help with?' field
- [x] Crisis page

**Comment by sarahwelton** [comment]
Crisis page (#75) and success message (#108) have been covered by @indiamindwave24

**Comment by sarahwelton** [comment]
#95
