### ISSUE TITLE
Landing page: bug on long resource url expanding outside of box

### ISSUE THREAD

**Issue by Cleop** [LDMW/app#96]
On mobile and ipad:

<img src="https://cloud.githubusercontent.com/assets/16775804/25739802/611dd0b6-317b-11e7-8459-aeb0937386b8.png" width=250px />

**Comment by ellemindwave** [comment]
![screen shot 2017-05-08 at 12 21 04](https://cloud.githubusercontent.com/assets/26304634/25802100/c4a9b626-33e8-11e7-9748-add51014d83b.png)

**Comment by shouston3** [comment]
@ellemindwave 
The fix hadn't gone through to the app. I've just added it back in.
Should be fine now

**Comment by ellemindwave** [comment]
@Cleop Thanks - looks good now 👍
