### ISSUE TITLE
Backing up cms database

### ISSUE THREAD

**Issue by shouston3** [LDMW/app#99]
We could look at backing up the content already added to the cms:

It may be as simple as running:

```bash
heroku run "python manage.py dumpdata --natural-foreign --natural-primary" --app ldmw-cms > backup_05_05_dumpdata.json
```

That file will have all the changes made so far to the cms

**Comment by Danwhy** [comment]
That command won't quite work because of heroku's lack of a file system, but we could redirect the data straight into a backup database instead of a file

**Comment by shouston3** [comment]
Running that command created the file `backup_05_05_dumpdata.json` for me on my computer

**Comment by Danwhy** [comment]
Ah yeah of course, sorry. It might still be a good idea to have this run on every deploy and save into either a backup database or an s3 bucket though

**Comment by shouston3** [comment]
We are currently backing up the cms database each time we deploy to heroku using our deploy script (#192)

Will reopen if this resurfaces as an issue
